### ISSUE TITLE
feat: Create a header component

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#11]
### What feature?

- [x] Create a header component
- [x] Default avatar should show the first letter of the authenticated user name
- [x] Add header to the main page

### Screenshots

![Header](https://github.com/user-attachments/assets/c45aef3b-7b26-41bf-9500-49fbbc6c3624)

**Comment by AnnaRomaniuta** [comment]
Good job, thanks!
