### ISSUE TITLE
fix: "No token provided" error message appears when navigating to the "Access Management " page

### ISSUE THREAD

**Issue by AnnaRomaniuta** [BinaryStudioAcademy/bsa-2024-gitfit#117]
### Describe your issue

When attempting to access the Access Management page, the page fails to load properly. Instead of displaying the expected content, the user encounters two identical error messages. The error indicates that there is a problem with accessing the page, likely due to a missing or invalid token. 

### Steps to reproduce

1. Log in to the application.
2. Navigate to the Access Management page.
3. Pay attention to the message "No token provided."

### What was the actual result?

The Access Management page doesn't open and a double error message appears.

### What was the expected result?

The Access Management page opens and is fully available for use.

### Put here any screenshots or videos (optional)

[video](https://app.screencast.com/Mj4pHiyQThj74)

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Blocker (S1)

**Comment by VeronikaHordus** [comment]
Looks good to me, thanks!
