### ISSUE TITLE
fix: Loader is missing when switching between pages

### ISSUE THREAD

**Issue by VeronikaHordus** [BinaryStudioAcademy/bsa-2024-gitfit#119]
### Describe your issue

When navigating between different pages of the application, there is no loading indicator displayed. A momentary white screen is displayed instead.

### Steps to reproduce

1. Login with valid data
2. Navigate to the "Projects" page
3. Switch to an another menu item such ar "Access Management"
4. Navigate back to the "Projects" page
5. Observe the transition berween page

### What was the actual result?

- There is a brief blank screen between page transitions.
- No loader is displayed.

### What was the expected result?

A loading indicator should be shown while loading new page.

### Put here any screenshots or videos (optional)

https://github.com/user-attachments/assets/d755e13a-83a4-43d2-90d4-ded36a70a87d

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Major (S3)

**Comment by AnnaRomaniuta** [comment]
Perfect, thanks.
