### ISSUE TITLE
feat: Create a sidebar component

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#12]
### What feature?

- [x] Create a sidebar component
- [x] Add the sidebar to the main page
- [x] `Projects` item should lead to `/` route

### Screenshots

![Sidebar](https://github.com/user-attachments/assets/8f9aff70-8c29-40ad-a08d-5f1bfff3e2b3)

**Comment by VeronikaHordus** [comment]
Good job, thank you !
