### ISSUE TITLE
fix: Abscence of a logo on the Sign In and Sign Up page

### ISSUE THREAD

**Issue by VeronikaHordus** [BinaryStudioAcademy/bsa-2024-gitfit#121]
### Describe your issue

A broken image icon is shown at the Login and Sign up page on the place of logo.

### Steps to reproduce

1. Navigate to the login page of the application.
2. Observe the area where the logo is supposed to be displayed.

### What was the actual result?

A broken image icon is shown in place of the logo.

### What was the expected result?

The logo image should be correctly displayed on the login page. 
If the original logo is not availible, a valid placeholder image should be used to avoid a broken image icon.

### Put here any screenshots or videos (optional)

![Image](https://github.com/user-attachments/assets/ce2c3358-8217-4526-8651-c3e6355ea7c0)

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Minor (S4)

**Comment by AnnaRomaniuta** [comment]
@kolibri753 Hi! I have a question, maybe these changes haven`t yet appeared in the development environment. The logo design also has decorative elements in the corporate color, but they are currently missing.

![Image](https://github.com/user-attachments/assets/7212f60e-d891-4d1a-99ca-84031214849b)

**Comment by AnnaRomaniuta** [comment]
Good work, thanks! As for the background, a separate bug report will be create.
