### ISSUE TITLE
feat: Add route protection

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#13]
### What feature?

- [x] Add authorization plugin to protect endpoints ([Fastify Plugins](https://fastify.dev/docs/latest/Reference/Plugins/))
- [x] Inject signed user (from authentication token) to requests
- [x] Exclude sign-up and sign-in as white-routes

**Comment by VeronikaHordus** [comment]
Everything is fine, thank you ;)
