### ISSUE TITLE
feat: Sign Up page fields validation,  Sign up button inconsistent text

### ISSUE THREAD

**Issue by VeronikaHordus** [BinaryStudioAcademy/bsa-2024-gitfit#131]
### What feature?

1. Sign Up button text inconsistent to the Mockup. The text of the button should be Create Account.

2. Field validation rules : 
 Email  field: 

- The format should include a local part, an "@" symbol, and a domain part. 
- The length <50
Local part (before the “@”) : 
- should contain alphanumeric characters, optionally separated by dots, underscores, or hyphens;
- cannot start or end with a dot or contain consecutive dots;
Domain part (after the “@”): 
- must contain at least two characters;
- must contain at least one dot;
- should consist of alphanumeric characters (A-Z, a-z, 0-9) and hyphens;

Name field:
- The name can contain any characters, including letters, numbers, spaces, and special characters;
- at least 3 characters;
- max 50 characters

Password must include: 

- At least 5 characters ;
- Not more than 50 characters
- At least 1 uppercase letter (A-Z);
- At least 1 lowercase letter  (a-z);
- At least 1 number ;
- At least 1 special character (e.g., !@#$%)"

### Screenshots

![image](https://github.com/user-attachments/assets/5309fcbd-e0aa-4af7-bbb2-fe98174efb21)

**Comment by kolibri753** [comment]
Clarification (about Email):

1. Domain Part: Should the dot (.) in the domain part be followed by at least two letters? For example, is username@example.c valid, or should it be rejected?
2. Local Part: Is a dot followed by a hyphen (.-) allowed in the local part? For instance, would user.-name@example.com be valid?

P.S. I believe both cases are invalid but wanted to confirm.

**Comment by VeronikaHordus** [comment]
I believe its good to make both ways invalid (sorry for long responce). 
I will add your clarifications in main info for validation, thanks!

**Comment by AnnaRomaniuta** [comment]
@kolibri753 Hello, I'm a little confused, maybe you can help me. When I try to register with an invalid address, for example without a domain part or without a special character @, I receive a message from the browser, not from the application![Image](https://github.com/user-attachments/assets/b4695128-531d-46d9-a6fc-44b18c6fc7b5)

**Comment by AnnaRomaniuta** [comment]
In general, everything works and looks good, a bug has been created for some discrepancies. Good job!
