### ISSUE TITLE
fix: The size of the user popup and the font of the elements don't match the layout

### ISSUE THREAD

**Issue by AnnaRomaniuta** [BinaryStudioAcademy/bsa-2024-gitfit#136]
### Describe your issue

1. The user's popup window is smaller than shown on the layout.
2. The elements of the user popup window "Profile" and "Log out" have the font Arial, and the layout is Inter.

### Steps to reproduce

**Pre-condition:** User is logged in.
1. Click the "Avatar" icon located in the header
2. Observe the "User Popup" that appears
3. Check the popup size
4. Check the font of the "Profile" and "Log out" elements

### What was the actual result?

1. The size of the user popup window 221.71х145.5 рх.
2. The font of the "Profile" and "Log out" elements of the user popup is Arial

![Image](https://github.com/user-attachments/assets/ac3b8e8d-2518-475a-9bac-4ad4ea64887f)

![Image](https://github.com/user-attachments/assets/342d65bb-b489-4a4c-b3e8-8f1c12892fbf)
![Image](https://github.com/user-attachments/assets/43a01e2e-3d66-4736-89d9-0bce978ec533)

### What was the expected result?

1. The size of the user popup window width 250 рх.
2. The font of the "Profile" and "Log out" elements of the user popup is Inter.

![Image](https://github.com/user-attachments/assets/661287ca-b030-4eaa-964b-b9d3a6b4b90a)
![Image](https://github.com/user-attachments/assets/0ffe3f1a-fe44-4089-9778-17c6e8757a1e)
![Image](https://github.com/user-attachments/assets/584e09c9-d230-43a7-987a-fec2b0c828e1)

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Trivial (S5)

**Comment by Vitaliistf** [comment]
Seems like I've fixed it. Waiting for the merge.

**Comment by AnnaRomaniuta** [comment]
Good job! Thanks!
