### ISSUE TITLE
feat: Add an ability to create and view project groups

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#139]
### What feature?

- [x] Add options icon to the Project details page.
- [x] On icon click, an options menu should appear with the "Manage Access" option.
- [x] On the "Manage Access" option click, a user should be navigated to the page similar to the root "Access Management". It should display the users table and groups table (project groups).
- [x] Add breadcrumbs to the page.
- [x] Add a "Create New" button near the Groups table.
- [x] When the button is clicked, a modal to create a new group should be displayed.
- [x] The user must select at least one user for the group.
- [x] Group can exist without permissions enabled.
- [x] After group creation, the new group should appear at the top of the Groups table.

Notes: These groups are unrelated to the user groups and permissions table. Project groups and project permissions should be used instead.

The backend part for the group creation is added here: #108 

### Screenshots

![Image](https://github.com/user-attachments/assets/34eec353-1370-41ad-8b48-82ff9936e68e)

![Image](https://github.com/user-attachments/assets/64a725ab-8959-4146-b0af-c9b26f4fb4fb)

![Image](https://github.com/user-attachments/assets/60b85f5a-c123-42c2-ab3a-d4fd096dc668)

**Comment by AnnaRomaniuta** [comment]
**User Story:**
As a user, I want to create and view project groups in the "Access Management" section to manage project access efficiently. 

**Acceptance Criteria:**
1. An options icon should be available on the Project Details page, allowing users to access additional project management features.
2. Clicking the options icon should reveal a menu with a "Manage Access" option, which redirects the user to a page displaying users and project groups tables.
3. A breadcrumbs trail should be present at the top of the "Access Management" page to help users navigate within the project hierarchy.
4. A "Create New" button should be visible near the Groups table, enabling users to initiate the creation of a new project group.
5. Upon clicking the "Create New" button, a modal should open, allowing users to fill out the group details, including a name, user selections, and permissions.
6. Users must select at least one user to form the group.
7. After submitting the form, the newly created group should immediately appear at the top of the Groups table.

**Comment by AnnaRomaniuta** [comment]
Everything looks good! Good job!
