### ISSUE TITLE
feat: Add an ability to delete personal account

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#146]
### What feature?

- [x] Add an ability to delete personal account.
- [x] On Delete button click, there should be a confirmation modal.
- [x] After the confirmation user account should be deleted (soft delete).

### Screenshots

![Image](https://github.com/user-attachments/assets/b938a60f-ed9f-4d15-ad2e-c5d189a1f49e)

**Comment by VeronikaHordus** [comment]
**User story**

As a user, I want to delete my personal account so I can permanently remove my data from the platform If there is no needed for their presence anymore.

**Access criteria**
1. The Delete account button is accessable at the buttom of the user's Profile page.
2. The Confirmation modal consist information that the User's data will be deleted permanently and all assotiated data will be lost. And the "Click 'confirm' to proceed" text is shown as the last sentence.
3. A final confirmation button, such as "Confirm" must be clicked to proceed.
4. Upon confirmation, user is being redirected to the Sign In page.
5. An attempt to log in with deleted account should result a Invalid credentials toast notification (as for Non-registered users).

**Comment by VeronikaHordus** [comment]
The functionality works appropriate 👍 Thank you ! 
I am not fully satisfied with the text on confirmation modal and confirmation button, but i will keep it in feature request.
