### ISSUE TITLE
feat: Add breadcrumbs to the project details page

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#165]
### What feature?

- [x] Add breadcrumbs to the project details page.
- [x] The last item should display the current project name.

### Screenshots

![Image](https://github.com/user-attachments/assets/50090d33-eca3-4c32-b8c2-164590ee5fa3)

**Comment by AnnaRomaniuta** [comment]
Everything works fine, thanks!
