### ISSUE TITLE
feat: Add an ability to save and retrieve activity

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#181]
### What feature?

We will have a script that automatically sends an array of statistic records. It will include git emails, date, and number of commits. We need to add an ability to save this statistic to the backend and retrieve it.

- [x] Add a contributors table (columns: id, created_at, updated_at, and name). 
- [x] Add git_emails table (columns: id, created_at, updated_at, contributor_id, email). 
- [x] Add activity_logs table (columns: id, created_at, updated_at, git_email_id, project_id, created_by_user_id, date, commits_number)
- [x] We will have a different type of authorization for the POST method. It will be in Bearer format, but instead of a usual token, we will get project_api_key #180. `created_by_user_id` and `project_id` should be taken from this key after encoding it and finding in the db. For GET request, we will have the usual authorization.
- [x] We will receive records grouped by date with author name, email, and commits_number as payload for POST request.
- [x] For each git_email, that doesn't exist yet, we need to create a contributor record first and then use it to create a record in the git_emails table. Git_email record cannot exist without contributor_id. A contributor's name can be taken from the author's email.
- [x] Add an endpoint to retrieve activity records. They should contain contributor data attached.

Example of payload (can be changed if needed or if another format is more convenient)
```json
[
  {
    "date": "2024-09-01",
    "items": [{
      "authorName": "John Doe",
      "authorEmail": "john.doe@gmail.com",
      "commitsNumber": 1,
    }],
  }
]
```

**Comment by VeronikaHordus** [comment]
User Story: 
As a manager, I want the application to automatically save and retrieve contributors statistics from Git, so that I can analyze developer activity and project progress over time.

Acceptance Criteria:
1. The script runs in the background, collects repository statistics, and periodically sends them to the backend.

**Comment by sandrvvu** [comment]
@liza-veis Should this feature be implemented as a separate activity module with its own controller, service, and models, right?

**Comment by liza-veis** [comment]
> Should this feature be implemented as a separate activity module with its own controller, service, and models, right?

yes

**Comment by VeronikaHordus** [comment]
All good!
