### ISSUE TITLE
feat: Add a character counter for the "Description" field in the project creation form

### ISSUE THREAD

**Issue by AnnaRomaniuta** [BinaryStudioAcademy/bsa-2024-gitfit#188]
### What feature?

- [x] Add a character counter below the "Description" text area in the project creation form, displaying the current character count in the format "X/1000". 

**User Story:**
As a user, I want to see a character counter below the "Description" field while creating a project, so that I can keep track of how many characters I have entered and ensure I don’t exceed the 1000-character limit.

**Acceptance Criteria:**
1. A character counter shall be displayed below the "Description" field in the format "X/1000".
2. The counter shall dynamically update as the user types, reflecting the current number of characters entered.
3. The "Description" field shall allow a maximum of 1000 characters.
4. If the user reaches the character limit, no further characters can be entered and a red validation message is displayed below the "Description Name" field: "Description is too long (> 1000 symbols)."

**Comment by AnutkaGn** [comment]
I'm not sure, but this problem will only be in development. This will not be in the production.
This error appears because we have StrictMode on the frontend (if you remove it or make a build, only one message appears). As far as I know, there is no StrictMode in production, it is used only in development.

**Comment by VeronikaHordus** [comment]
As for me - all good, thank you!
Will ask Anna to check it out as well.

**Comment by VeronikaHordus** [comment]
All good<3
