### ISSUE TITLE
fix: The success message for profile update doesn`t match the specification

### ISSUE THREAD

**Issue by AnnaRomaniuta** [BinaryStudioAcademy/bsa-2024-gitfit#193]
### Describe your issue

Upon updating the profile information, the success message displayed to the user differs from the one defined in the specification. According to the requirements, the success message should read "Your profile has been successfully updated." However, the current message shown is "Successfully updated profile information." 

### Steps to reproduce

1. Log in to the application.
2. Navigate to the "Profile" page by clicking the avatar icon in the header.
3. Select "Profile" from the dropdown.
4. Edit the data in the "Name" field.
5. Click the "Update Profile" button.
6. Observe the success message after the profile is updated.

### What was the actual result?

The success message displayed is: "Successfully updated profile information."

![Image](https://github.com/user-attachments/assets/67c03ffc-8e99-4648-a837-d97b6283aa27)

### What was the expected result?

The success message should be: "Your profile has been successfully updated."

![Image](https://github.com/user-attachments/assets/f8c4ac12-b2fb-4338-b63e-948d226a56b9)

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Trivial (S5)

**Comment by AnnaRomaniuta** [comment]
@perekotypole Hi! I'm a bit confused but I don't see any change. Maybe the changes haven't been deployed yet and I need to wait, please let me know)))

**Comment by AnnaRomaniuta** [comment]
@perekotypole All right! But I don't know what to do about it. Can you fix it somehow?

**Comment by perekotypole** [comment]
Yep, I will add it with my current PR to not create a mess

**Comment by AnnaRomaniuta** [comment]
I saw all the changes, good work, thank you!
