### ISSUE TITLE
fix: Inconsistent title alignement on the Update project modal

### ISSUE THREAD

**Issue by VeronikaHordus** [BinaryStudioAcademy/bsa-2024-gitfit#198]
### Describe your issue

The title of the Update project modal placed lower than on the mockup.

### Steps to reproduce

1. Open the Projects page
2. Click on the options button on  the right side of the Project card
3. Click Edit button
4. Take a look at the location the Modal's title

### What was the actual result?

The title is placed lower than the very top of the modal and goes closer to the Name field creating a noticible empty spot at the top of the window.

### What was the expected result?

The title is placed accordingly to the mockUp

### Put here any screenshots or videos (optional)

![Image](https://github.com/user-attachments/assets/c753b36f-49ba-4b51-a94b-3f7e5dc203b1)

![Image](https://github.com/user-attachments/assets/ec52f820-9146-4c26-a514-910f63bf2766)

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Minor (S4)

**Comment by sandrvvu** [comment]
@VeronikaHordus Hey! We are using one component for all modals. And I assume someone has already fixed this issue

![Image](https://github.com/user-attachments/assets/36135fa2-4674-41bb-bd32-4a19076c6743)

**Comment by VeronikaHordus** [comment]
Checking if the bug is still reproducible

**Comment by VeronikaHordus** [comment]
Issue is not reproducible anymore!
