### ISSUE TITLE
feat: Add a not found page

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#20]
### What feature?

- [x] Create not found page
- [x] User should be redirected to the not found page on an unknown route
- [x] Back to home button should lead user to the `/` route

### Screenshots

![Not Found](https://github.com/user-attachments/assets/dc57c8c2-39d0-47de-91d6-d8d260fe0151)

**Comment by VeronikaHordus** [comment]
All work as required.
