### ISSUE TITLE
feat: Improve toast notification position and design

### ISSUE THREAD

**Issue by AnnaRomaniuta** [BinaryStudioAcademy/bsa-2024-gitfit#201]
### What feature?

- [x] Move the toast notification to the left side of the screen to make it less intrusive and reduce user distraction.
- [x] Adjust the notification colors to improve contrast with the main background, just like the notifications on Figma. 
- [x] Add a subtle border around the notification or lighten the background, similar to modal windows.

**User Story:**
As a user, I want toast notifications to be less intrusive and more visually distinct so that I can be alerted without my workflow being interrupted.

**Acceptance Criteria:**
1. Move the toast notification to the left side of the screen.
2. Adjust notification colors for better contrast with the background.
3. Add a border or lighten the background for clearer visibility.
4. Ensure notifications are readable and unobtrusive.

**Comment by AnnaRomaniuta** [comment]
It may be necessary to try different options and discuss it in the chat to choose the best one.

**Comment by VeronikaHordus** [comment]
Final point of the toast notification location after discussion : The top right corner of the page.

Looks good for both - error and confirmation notifications 👍
