### ISSUE TITLE
feat: Improve avatar visibility

### ISSUE THREAD

**Issue by AnnaRomaniuta** [BinaryStudioAcademy/bsa-2024-gitfit#202]
### What feature?

- [x] Add a border around the avatar, change the background color, or increase the size of the letter to make it more noticeable.

**User Story:**
As a user, I want the avatar to be more noticeable so I can easily identify it on the page.

**Acceptance Criteria:**
1. Add a border, change the background color, or increase the letter size for better visibility.
2. Ensure the avatar is visually distinct and easy to locate.
3. The avatar remains visually clear and understandable on all pages.

**Comment by VeronikaHordus** [comment]
I'm satisfied with the result, thank you!
