### ISSUE TITLE
feat: Add cursor pointer for select

### ISSUE THREAD

**Issue by AnnaRomaniuta** [BinaryStudioAcademy/bsa-2024-gitfit#204]
### What feature?

- [x] Add a cursor pointer for the select field and its options to improve user interaction.

- [x] Apply purple color on hover for the select field and its options, ensuring consistency with other input elements.

- [x] Highlight the selected options with a different color (e.g., grey) to differentiate them from unselected options.

**User Story:**
As a user, I want clear visual feedback when interacting with select fields, so I can easily understand which option I am selecting and improve my experience.

**Acceptance Criteria:**

1. Cursor pointer: add a cursor pointer for the select field and its options, ensuring consistent behavior across all select components (e.g., rows per page in tables).
2. Hover state: apply purple color on hover for the select field and options, similar to the hover effect on other input elements.
3. Selected option highlight: highlight selected options with a different color, such as grey, to distinguish them from other unselected options.

**Comment by perekotypole** [comment]
Hover/focus on select control as on input elements:
![Hover on select control](https://github.com/user-attachments/assets/23c82aaf-b0f5-4c60-858a-6e6e38754f47)

Hover/focus on option as on buttons:
![Hover on option](https://github.com/user-attachments/assets/c26bcca3-5f96-4625-b3fc-74a029fb8208)

**Comment by AnnaRomaniuta** [comment]
@perekotypole Hi! This design fits, looks good.

**Comment by VeronikaHordus** [comment]
Looks good for me !
