### ISSUE TITLE
feat: Display message for empty tables

### ISSUE THREAD

**Issue by AnnaRomaniuta** [BinaryStudioAcademy/bsa-2024-gitfit#206]
### What feature?

- [x] Add a default message "There is nothing yet"  to be displayed when a table has no rows.

- [x] The message is styled appropriately to match the overall UI and is clearly visible.

- [x] Implement this feature for all tables across the application where data might be empty (users table, groups table, projects list, contributors table, analytics table).

**User Story:**
As a user, I want to see a message when a table is empty, so I understand that no data is available rather than thinking the table failed to load.

**Acceptance Criteria:**
1. A default empty message "There is nothing yet" is displayed when a table contains no rows.
2. The message is styled consistently with the rest of the UI and is easily readable.
3. The message appears across all tables in the application when no data is present.
4. The message disappears automatically once data is loaded into the table.

**Comment by VeronikaHordus** [comment]
Looks good. Thanks fot the feature and for help with an approach of testing!
