### ISSUE TITLE
feat: Create a modal component

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#21]
### What feature?

- [x] Create a common modal component
- [x] Should accept title as parameters and children as body
- [x] On cross icon click, the modal should be closed
- [x] On outside click, the modal should be closed
- [x] For testing purposes, add a button to the main page to open a modal

### Screenshots

![Modal](https://github.com/user-attachments/assets/f98946ca-a972-40d9-b7a4-c90cd9ac7cce)

**Comment by VeronikaHordus** [comment]
Good job, thanks
