### ISSUE TITLE
fix: The notification for an expired token appears twice when triggered

### ISSUE THREAD

**Issue by AnnaRomaniuta** [BinaryStudioAcademy/bsa-2024-gitfit#217]
### Describe your issue

When the token expires, the application displays two identical notifications instead of one. This issue occurs when the user’s session times out or when attempting an action after token expiration.

### Steps to reproduce

1. Log into the application.
2. Wait for the token to expire.
3. Perform an action that requires authentication (e.g., page refresh).
4. Notice that two duplicate notifications are displayed about the expired token.

### What was the actual result?

Two identical expired token notifications appear at the same time.

### What was the expected result?

Only one notification should appear informing the user that the token has expired.

### Put here any screenshots or videos (optional)

![Image](https://github.com/user-attachments/assets/6f07e7a4-ec5b-4c9a-bff0-e75b7969bb7b)

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Minor (S4)

**Comment by AnutkaGn** [comment]
I'm not sure, but this problem will only be in development. This will not be in the production.
This error appears because we have StrictMode on the frontend (if you remove it or make a build, only one message appears). As far as I know, there is no StrictMode in production, it is used only in development.

**Comment by AnnaRomaniuta** [comment]
@AnutkaGn Hi! I've seen this double message locally, while on the dev environment a single expired token message, or it doesn't matter either because it's all development?

**Comment by AnutkaGn** [comment]
I'm not sure about that. Perhaps we should ask @liza-veis

**Comment by liza-veis** [comment]
Yes, that's expected, currently for development environment we're using production mode, to be able to test functionality properly.
