### ISSUE TITLE
feat: Make buttons 100% width by default

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#232]
### What feature?

- [x] Make the Button component 100% width by default.
- [x] Remove the unnecessary properties like `flex-direction: column` from button wrappers across the app and check that everything stays the same.

For testing:
We need to check that all buttons look the same as in the design and before the changes.

**Comment by AnnaRomaniuta** [comment]
Everything looks good! Good job!
