### ISSUE TITLE
feat: Refactor existing sub-components to be stored under the libs folder

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#233]
### What feature?

Currently, we have some places with a path like the following `/src/pages/profile/components`, we need to move sub-components under the `libs` folder so that the path becomes: `/src/pages/profile/libs/components`. This needs to be done for pages sub-components and components sub-components.

**Comment by VeronikaHordus** [comment]
@liza-veis  I've checked the current path and is is suitable to the requirement. I am only not sure if all needed components are there. At the momet it looks like that :
https://github.com/user-attachments/assets/b5d17352-ca18-4649-a762-f0ed9b9568af

I suppose this is good, am I right?

**Comment by liza-veis** [comment]
yes, it's ok
