### ISSUE TITLE
fix: Name field doesn`t accept hyphen on Sign-Up page

### ISSUE THREAD

**Issue by AnnaRomaniuta** [BinaryStudioAcademy/bsa-2024-gitfit#236]
### Describe your issue

The "Name" field on the Sign-Up page should accept latin letters, hyphen  and spaces, with a minimum of 3 characters and a maximum of 50 characters. 

### Steps to reproduce

1. Navigate to the Sign-Up page.
2. Enter a name with hyphen (e.g., "Anna-Maria") in the "Name" field.
3. Submit the form.

### What was the actual result?

The "Name" field rejects names containing a hyphen and displays an error.

### What was the expected result?

The "Name" field should accept names with latin letters, hyphen and spaces,  as long as they meet the length criteria (at least 3 characters and max 50 characters).

### Put here any screenshots or videos (optional)

https://github.com/user-attachments/assets/71c1e250-5105-4e70-af20-c43eaccfd00f

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Major (S3)

**Comment by kolibri753** [comment]
Sorry, let me clarify. The first (or second :smiley:) variant I implemented included this, but I was advised to simplify the regex. Specifically, the rule was to allow only Latin characters for names. However, if the requirement is to also include numbers and special characters, I can certainly adjust it accordingly.

**Comment by liza-veis** [comment]
@AnnaRomaniuta @kolibri753 I think we don't need to allow special characters or numbers for names 🤔 It's not a username but rather we expect users to input their full names in format `John Doe`

**Comment by AnnaRomaniuta** [comment]
@liza-veis Thanks for the reply but I'm a bit confused. Because we made changes to the specification at the recommendation of the product owner that the name field accepts all characters. Ok, I think we need to adjust the requirements and leave the field accepting only letters and spaces. But I also want to note that there are people with a double name, for example Anna-Maria.![Image](https://github.com/user-attachments/assets/e49a9995-3e3d-41e6-bb4a-dcc294054dd3)

**Comment by liza-veis** [comment]
@AnnaRomaniuta Hm, that's a good point, I would allow `-` for the name. But numbers and other special chars I think are not needed

**Comment by AnnaRomaniuta** [comment]
@liza-veis I think so too, I'll fix it in the spec then. Should I create a new bug report only for adding a hyphen, and close this one?

**Comment by liza-veis** [comment]
I think we can just update this issue, no need to create a separate ticket.

**Comment by kolibri753** [comment]
I'm not sure how we can best modify the message in this case, or if it can stay the same `Name must contain only Latin letters.`

**Comment by liza-veis** [comment]
Agree, let's leave the same message.

**Comment by AnnaRomaniuta** [comment]
Everything works and looks great! Thank you.
