### ISSUE TITLE
feat: Create a select component

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#24]
### What feature?

- [ ] Create a common select component (use [react-select](https://www.npmjs.com/package/react-select))
- [ ] Should have multi-select and single-select variants

### Screenshots

![Select](https://github.com/user-attachments/assets/9b0d992e-6f45-404b-935b-bb17217ea10d)
![Image](https://github.com/user-attachments/assets/4fa0aab3-c048-42e6-9e82-74e5c961576f)

**Comment by VeronikaHordus** [comment]
I will wait when more elements with component would appear for testing, now select component is only as a part of paginator component. Can't see properly the way it works there.

**Comment by VeronikaHordus** [comment]
Seems to work perfect, thank you!
