### ISSUE TITLE
feat: Create a script for collecting statistics

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#247]
### What feature?

- [x] Create a script for collecting statistics on background.
- [x] The script will be a separate app inside `/apps` directory, @liza-veis will set up a workspace for it. 
- [x] The script will need to be a cli, we will publish it on npm later.
- [x] The cli command should accept a project repository path, project api key and user id (will be used for created_by in statistics) as parameters and start a background job.
- [x] Every 3 hours the job will need to fetch the latest changes, collect statistics from remote for the day, and send a request to update it on the backend.
- [x] For authorization we will use a project API key and send it in Bearer format.

Notes:

Background script example - https://github.com/jhladkov/CLI
Reference script for collecting activity - [activity-report.txt](https://github.com/user-attachments/files/16942696/activity-report.txt)

Generating API key #180 (PR #223)
Saving activity logs #181 (PR #221)

**Comment by s1rserg** [comment]
@liza-veis I wanted to clarify a couple of points
* Since this will be a separate app, how closely should it adhere to our current project structure and rules? For example, should it be a TypeScript app with base modules and other backend conventions we currently follow?
* Regarding the user ID, should I process or handle it in any specific way, or can I simply return it along with the collected stats?

**Comment by liza-veis** [comment]
> @liza-veis I wanted to clarify a couple of points
> * Since this will be a separate app, how closely should it adhere to our current project structure and rules? For example, should it be a TypeScript app with base modules and other backend conventions we currently follow?

The structure will be similar to the backend. We will have the same configs and project setup.

> * Regarding the user ID, should I process or handle it in any specific way, or can I simply return it along with the collected stats?

Yes, you can just return it, without additional processing.

**Comment by s1rserg** [comment]
@liza-veis, just to confirm, should I expect the workspace to be completed today, or will it be after the demo tomorrow? I assume that if it's done later, I might need to refactor based on the final configuration, so there's no point in guessing how it will be set up now.

**Comment by liza-veis** [comment]
Workspace means that we will have a separate app with separate configs for the cli script, which will have index.ts as an entry point. It will be set up by the end of the day I believe.

**Comment by VeronikaHordus** [comment]
Not ready for testing yet due to the abscence of the shared package

**Comment by VeronikaHordus** [comment]
It looks good 👍
