### ISSUE TITLE
feat: Add contributors page

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#250]
### What feature?

- [x] Add contributors item to the sidebar.
- [x] Add contributors table with all the contributors. It should contain Name, Git Emails and Projects columns.
- [x] Projects - are all projects associated with the contributor through git emails and activity logs.

PR where contributors table is added #221

### Screenshots

![Contributors](https://github.com/user-attachments/assets/5d314618-3f44-488c-8a33-7b951f1d4a8b)

**Comment by liza-veis** [comment]
You will need to re-use services/repositories created in #221, but you need to add everything else needed for your task

**Comment by Vitaliistf** [comment]
> You will need to re-use services/repositories created in [#221](https://github.com/BinaryStudioAcademy/bsa-2024-gitfit/pull/221), but you need to add everything else needed for your task

Okay, I'll try to figure it out.

**Comment by VeronikaHordus** [comment]
Looks good!
