### ISSUE TITLE
fix: restrict user manage group 

### ISSUE THREAD

**Issue by AnutkaGn** [BinaryStudioAcademy/bsa-2024-gitfit#254]
### Describe your issue

All users can create a group

### Steps to reproduce

1. Log in to the system
2. Create a group

### What was the actual result?

All users can create a group

### What was the expected result?

Only users with "manage_user_access" permission can create a group

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Blocker (S1)

**Comment by AnnaRomaniuta** [comment]
@AnutkaGn If I understand everything correctly, if I don't have "manage_user_access" permission I don't even see access management on the sidebar.

**Comment by AnutkaGn** [comment]
That's right. Also, the user cannot create a group without this permission. You can test it in Postman (request to `http://localhost:3001/api/v1/groups`)

**Comment by AnnaRomaniuta** [comment]
![Image](https://github.com/user-attachments/assets/94009778-6445-4a95-97ae-949a6eed215c)
Maybe I did something wrong, but when I leave the permission parameters blank, the group is created.

**Comment by AnutkaGn** [comment]
So it should be.
It is necessary that the user cannot create a group if he does not have permission to do so. If it does not have permissions, then an error message should appear that no permissions are required.
As I understand now, the user from whom you made the request is attached to the admin group, so he has this permission and can create a group. Now you can try another user (who won't be in this group) and then there should be an error message.

**Comment by AnnaRomaniuta** [comment]
1. I created a new user at the front (there he did not have access to access management)
2. I looked up his ID in the database
3. Through Postman, I created a request to create a new group with this user and it was created.
So, it turns out that my user does not have access on the front, and through the backend I created a new group with the ID of this user.

**Comment by AnutkaGn** [comment]
I just tested it through postman
A user who does not have permissions:
![image](https://github.com/user-attachments/assets/b9c4f77c-d3f3-4d69-a047-51e29f95ab1c)
A user who has permissions:
![image](https://github.com/user-attachments/assets/9276f248-ec1d-4f2d-8f5a-f81481045552)

Maybe you didn't change the token when you made the request, and you requested with the admin token anyway?

**Comment by AnnaRomaniuta** [comment]
I still recorded a video, but I'm creating a group(((https://github.com/user-attachments/assets/305da78d-e0a3-4d3a-bb2f-d1a42934e9a8

**Comment by AnutkaGn** [comment]
I did the same steps, but I can't create a group. I still don't understand why this happens. From which branch did you pull the changes? Maybe you don't have the latest version of the code?

**Comment by AnnaRomaniuta** [comment]
Yeah, sorry, that's my failure. I don't have the latest version, now I'm trying to update it.

**Comment by AnnaRomaniuta** [comment]
Checked! Everything works correctly)))  Sorry for strange questions, I had this problem, I was pulling changes from the wrong branch.
