### ISSUE TITLE
feat: Do not return project description on get all request

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#259]
### What feature?

- [x] Do not return project description from the backend on `GET /projects` endpoint as it's not used

**Comment by AnutkaGn** [comment]
@liza-veis, I had a problem when I made the backend not return the project description when I request to get all projects.

If you open the modal window for editing the project, it looks like this before the changes.
![image](https://github.com/user-attachments/assets/92888e3b-a788-4e21-adef-5f5d7df669d4)

If the backend does not return a description, then the modal window looks like this
![image](https://github.com/user-attachments/assets/b9fe4192-0de5-4e05-b831-328d4c390cf7)

And another question, can I make a separate type, where the project will have only an ID and a name? Now I did like this `items: Omit<ProjectGetAllItemResponseDto, "description">[]`

**Comment by liza-veis** [comment]
1. Let's fetch this specific project when we open the modal, we can re-use the actions we have when we open project details page.
2. ProjectGetAllItemResponseDto shouldn't have description, we need to have a separate type - ProjectGetByIdResponseDto which will have it. Take a look at this PR #223

**Comment by AnnaRomaniuta** [comment]
Good job! Thanks!
