### ISSUE TITLE
feat: Add infinite scroll to the projects list

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#276]
### What feature?

- [x] Display a specific amount of projects in the project list (10-15).
- [x] When the user reaches the end of the container, load another batch of projects. Use [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) for this.
- [x] Make sure it works ok with the search. We need to reset the items we loaded after the search.

**Comment by VeronikaHordus** [comment]
The scroll getting stuck within some certain projects and scroll them over and over again. 
The Error message "Encountered two children with the same key, `27`" is shown in console for a group that is shown repitedly.

https://github.com/user-attachments/assets/8a1782e2-161c-4f19-ba99-0a40ea9a6c39

(https://github.com/user-attachments/assets/09b4e2c9-2a45-43f7-b0dd-8ac9e3f99b5d)

**Comment by VeronikaHordus** [comment]
Looks good ! Thanks
