### ISSUE TITLE
feat: Add an ability to copy project api key

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#284]
### What feature?

- [x] Add an ability to copy a project api key.
- [x] User should also be able to copy the key manually by selecting it inside the input. We need to remove ellipsis for this.

### Screenshots

![Setup analytics modal (1)](https://github.com/user-attachments/assets/12086ec1-002c-47b0-8561-d391ffa428ea)

**Comment by kolibri753** [comment]
I'm a bit confused about what the default behavior for text overflow in an input should be.

Ellipsis?
![image](https://github.com/user-attachments/assets/03451b7c-1a16-43d6-ac1c-60e61d30f753)

And for this task I can modify the Input component by adding a `textOverflow?: "clip" | "ellipsis" | "visible";` property. So it should look like this:
![image](https://github.com/user-attachments/assets/d3828b1a-7813-4015-a5fa-e3ef40ad4187)

**Comment by kolibri753** [comment]
And I'm thinking of using isReadOnly when the API key is already generated, and isDisabled when the key isn't

**Comment by liza-veis** [comment]
> Does it look correctly on images? Or vice versa?

It looks correctly on the image and we don't need the ellipsis property, we want user to be able to keep the content of the input.

> And I'm thinking of using isReadOnly when the API key is already generated, and isDisabled when the key isn't

Let's use isDisabled property only, but change the cursor to the usual input cursor.

**Comment by AnnaRomaniuta** [comment]
Everything works fine! Good job!
