### ISSUE TITLE
fix: The page reloads after generating the API key

### ISSUE THREAD

**Issue by VeronikaHordus** [BinaryStudioAcademy/bsa-2024-gitfit#289]
### Describe your issue

After a successfull API  key generation the page reload is triggered.

### Steps to reproduce

Pre-conditions: User is logged in. User have "View All Projects" permission.
1. Navigate to the Projects page
2. Open any Specific project from the list
3. Click "Setup Analytic" button
4. In the opened  Modal window click "Generate" button 
5. Observe the page behavior

### What was the actual result?

The page reload triggers abruptly after generating the API key.

### What was the expected result?

The API key is generated. The page is not reloading.

### Put here any screenshots or videos (optional)

https://github.com/user-attachments/assets/49c05ec7-0363-4e64-90ac-943cf5a503d1

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Major (S3)

**Comment by AnnaRomaniuta** [comment]
Looks good! Thank you!
