### ISSUE TITLE
fix: The users are not sorted correctly at the "Users" table in the "Access Managment" page

### ISSUE THREAD

**Issue by VeronikaHordus** [BinaryStudioAcademy/bsa-2024-gitfit#290]
### Describe your issue

On the Access Management page, the "Users" table does not correctly sort users by the "Created At" date and time

### Steps to reproduce

Pre-conditions: User is logged in. User has a "Manage User Access" permission type.

1. Navigate to the "Access Management" page.
2. Observe the "Users" table.
3. Check the order of users in the "Created At" column.

### What was the actual result?

Users are not sorted by the "Created At" column. The order appears random.

### What was the expected result?

The "Users" table should display users sorted by the "Created At" column, with the newest users (most recent creation dates) appearing at the top. The new users after registration appear at the top of the Users list.

### Put here any screenshots or videos (optional)

![Image](https://github.com/user-attachments/assets/e73f3e27-2b44-4a14-9067-837afed6126a)

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Major (S3)

**Comment by AnnaRomaniuta** [comment]
Everything is perfect! Thank you!
