### ISSUE TITLE
feat: Add users column to the groups table

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#301]
### What feature?

- [x] Add `Users` column to the groups table.
- [x] The column should display a number of users in the group.

### Screenshots

Screenshot from another app:

![Image](https://github.com/user-attachments/assets/6435b26b-0b05-48d1-8f83-dd79df793578)

**Comment by AnnaRomaniuta** [comment]
Everything looks good and works well!
