### ISSUE TITLE
fix: Button names don`t match the design in "Setup Analytics"

### ISSUE THREAD

**Issue by AnnaRomaniuta** [BinaryStudioAcademy/bsa-2024-gitfit#308]
### Describe your issue

The "Setup Analytics" button on the "Project" page has the word "analytics" starting with a lowercase letter, but it should be capitalized as "Analytics".

### Steps to reproduce

1. Navigate to the "Projects" page.
2. Click on any project to open its details.
3. Observe the label of the "Setup Analytics" button.

### What was the actual result?

1. The "Setup Analytics" button label is "Setup analytics" with a lowercase "a".

![Image](https://github.com/user-attachments/assets/0f7cad62-697d-400e-be22-578fa1b5f9c0)

### What was the expected result?

1. The "Setup Analytics" button should be labeled as "Setup Analytics" with a capital "A".

![Image](https://github.com/user-attachments/assets/4b61147b-0176-4cae-bbda-a01ec06bbfc8)

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Trivial (S5)

**Comment by AnutkaGn** [comment]
I am working on the regeneration of the API key, so I made the "Regenerate" button (my [PR](https://github.com/BinaryStudioAcademy/bsa-2024-gitfit/pull/307))

**Comment by AnnaRomaniuta** [comment]
@AnutkaGn Thanks for the answer, we have already resolved it with Mykhailo)))

**Comment by AnnaRomaniuta** [comment]
Everything looks great!
