### ISSUE TITLE
fix: Incorrect message displayed after deleting all Projects

### ISSUE THREAD

**Issue by AnnaRomaniuta** [BinaryStudioAcademy/bsa-2024-gitfit#313]
### Describe your issue

When all projects are deleted, the message "No projects found matching your search criteria. Please try different keywords." is displayed. The correct message should be: "No projects created yet. Create the first project now."

### Steps to reproduce

1. Go to the "Projects" page.
2. Create several projects.
3. Delete all the projects.
4. Observe the message that appears.

### What was the actual result?

The message "No projects found matching your search criteria. Please try different keywords." is displayed after deleting all projects.

### What was the expected result?

The message "No projects created yet. Create the first project now." should be displayed when there are no projects.

### Put here any screenshots or videos (optional)

![Image](https://github.com/user-attachments/assets/958ff238-98dd-4c72-bcff-5a608596ec78)

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Minor (S4)

**Comment by AnnaRomaniuta** [comment]
@Fjortis Unfortunately, I don't see any changes. The message after deleting all projects didn't change.

**Comment by Fjortis** [comment]
Let me double check if something on main overwrote my changes

**Comment by Fjortis** [comment]
@AnnaRomaniuta It seems my changes were overwritten, i will get it done again

**Comment by AnnaRomaniuta** [comment]
Everything works fine! Thank you!
