### ISSUE TITLE
feat: Update validation message for email address field

### ISSUE THREAD

**Issue by AnnaRomaniuta** [BinaryStudioAcademy/bsa-2024-gitfit#314]
### What feature?

- [x] Replace the current validation message "Email is wrong." with a more descriptive message "Incorrect email format."on the Sign up and Sign in forms.

### Screenshots

![Image](https://github.com/user-attachments/assets/d75b23f3-0ab9-4b0f-b5b5-d96fce168f90)

**Comment by VeronikaHordus** [comment]
I do not see changes :(

**Comment by kolibri753** [comment]
Maybe it hasn't been added to the deployment yet. But if you're testing locally, you also need to run `npm run build:shared`

**Comment by VeronikaHordus** [comment]
Will check it ones again now with new deploy.

**Comment by VeronikaHordus** [comment]
Okay, sorry. Just wasn't in Deploy.
All good now, thank you!
