### ISSUE TITLE
feat: Add analytics table

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#327]
### What feature?

- [x] Add analytics table to the analytics page.
- [x] The user should be able to select a date range that is less than 1 month and the max date is today.
- [x] When user changes the date range, the columns in the table should match a new range and data should be updated.

### Screenshots

![Image](https://github.com/user-attachments/assets/34c88167-2263-4511-8a31-ef4b65c16a57)

**Comment by AnnaRomaniuta** [comment]
**User Story:**
As a user, I want to view an analytics table on the Analytics page, where I can select a date range (less than 1 month, with the max date being today) and see relevant data for that range.

**Acceptance Criteria:**

1. The user can select a date range that is less than 1 month, with the max date being the current day.
2. When the date range is changed, the table automatically updates its columns to reflect the selected dates.
3. The table displays contributors as rows and the selected dates as columns.
4. Each cell shows the number of commits made by a contributor on the corresponding date. If there are no commits, a minus sign (“-”) is displayed.

**Comment by VeronikaHordus** [comment]
5. The amount of availible years to be choosen on the Date range is 1 year from today. (The latest availible to be choosen date in the entire Datepicker should be one year from today)

(Additional point for the Date range)

**Comment by VeronikaHordus** [comment]
Good job, thank you!
