### ISSUE TITLE
fix: Search parameters persist after closing and reopening group Creation modal

### ISSUE THREAD

**Issue by AnnaRomaniuta** [BinaryStudioAcademy/bsa-2024-gitfit#331]
### Describe your issue

The previous search query remains in the "Search" field in the create new group modal and the filtered user list is still displayed, even after closing and reopening the modal. 

### Steps to reproduce

1. Go to the "Access Management" page.
2. Open the group creation modal.
3. Enter a search query in the "Search" field to filter users.
4. Close the group creation modal.
5. Reopen the group creation modal.
6. Pay attention that the search parameters are saved after closing.

### What was the actual result?

The previous search query remains in the "Search" field and the filtered user list is still displayed, even after closing and reopening the modal. The search parameters are saved until manually deleted.

### What was the expected result?

The "Search" field in the group creation modal should be empty after closing.

### Put here any screenshots or videos (optional)

https://github.com/user-attachments/assets/7bfc6f2c-5c15-4585-9e8f-4fa456762461

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Trivial (S5)

**Comment by AnnaRomaniuta** [comment]
@Fjortis The issue with the search parameters is fixed, but I noticed a different situation here. After closing the group creation modal window and reopening it, a double reload occurs. Perhaps this is due to corrections?  I can open a separate bug ticket for this.


https://github.com/user-attachments/assets/a60bbd5c-6257-4cd1-82bf-7db369f35b6a

**Comment by Fjortis** [comment]
I can get this sorted right away, this is due the corrections, we can start a separate issue. I can grab it right away

**Comment by AnnaRomaniuta** [comment]
@Fjortis Good. I`ll create a separate ticket and assign it to you)))
