### ISSUE TITLE
feat: Add notification for failed project activity update

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#336]
### What feature?

- [x] Add notifications icon and popup on UI.
- [x] During initial render, load all notifications (no need for real-time updates for now).
- [x] Add notifications module to the backend.
- [x] Inside projects service schedule a cron job, which will be triggered with the following interval and create appropriate notification which will indicate that statistics for the project were not updated for the N days:
  - 3 days
  - 7 days
  - after that, send a notification every 7 days.
 - [x] We only need to trigger this notification for projects that have `last_activity_date` not null. This column is added here #274 .

### Screenshots

![Screenshot 2024-09-16 at 17 34 17](https://github.com/user-attachments/assets/859a1de7-fe03-477a-9b6c-a62cd11ca8d2)

**Comment by AnnaRomaniuta** [comment]
**User Story:**
As a user, I want to receive notifications when project statistics are not updated for a certain period of time, so I can stay informed about project activity and take necessary actions.

**Acceptance Criteria:**

1. A notifications icon is displayed in the header, accessible from any page.
2. The relative time when the notification was received (3 days, 7 days, after that, send a notification every 7 days).
3. Notifications are only sent for projects with a valid last activity date.

**Comment by s1rserg** [comment]
@liza-veis, I need to clarify a few moments about backend.
1. So I need to create a notifications module and a notifications table for that. Should I omit status and type columns for now?
2. Notification table has receiver_user_id column. Does it mean that only one user should receive the notification about failed project activity update? It just seems odd that notifications explicitly connected to users and not to project groups.
3. Since analytics is updated every 3 hours should the notification cron job check for all project updates also every 3 hours and then compare last_activity_date to 3 days, 7 days and so on?

**Comment by liza-veis** [comment]
> 1. So I need to create a notifications module and a notifications table for that. Should I omit status and type columns for now?

yes, let's omit unnecessary columns for now.

> 2. Notification table has receiver_user_id column. Does it mean that only one user should receive the notification about failed project activity update? It just seems odd that notifications explicitly connected to users and not to project groups.

Notifications should be connected to users. We need to find all users that have access to the analytics: View All Projects, Manage All Projects (root permissions) or View Project, Edit Project, Manage Project (permissions for this project) and create notification for each of them (there should be an option for bulk creation).

> 3. Since analytics is updated every 3 hours should the notification cron job check for all project updates also every 3 hours and then compare last_activity_date to 3 days, 7 days and so on?

No, no need for this logic, because we won't delete notifications, once they are sent.

**Comment by s1rserg** [comment]
> No, no need for this logic, because we won't delete notifications, once they are sent.

Now i don't really understand how it should work. So the notification cron job should be global for all projects but run once a day or it should run separately for each project?

**Comment by liza-veis** [comment]
> Now i don't really understand how it should work. So the notification cron job should be global for all projects but run once a day or it should run separately for each project?

I see the logic like this: We run one cron job every day, and inside it, we fetch all projects where the last activity log is less than the current date by our first threshold. Filter projects where needed number of days passed (either 3, or the number is dividable by 7), then for each of this project we need to find all eligible users and create the same notification for each of those users.

**Comment by AnnaRomaniuta** [comment]
Looks good! Thanks for the testing tips!
