### ISSUE TITLE
feat: Display list of contributors on project details page

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#337]
### What feature?

- [ ] Display a list of all contributors on the project details page.

Needed endpoints are added here #334 

### Screenshots

![Image](https://github.com/user-attachments/assets/2f832346-e52d-4c72-abe7-604e7fc3779e)

**Comment by AnnaRomaniuta** [comment]
**User Story:**
As a user, I want to see a list of contributors on the project details page, so I can easily view who is involved in the project.

**Acceptance Criteria:**

1. A "Contributors" list is displayed on the project details page.
2. The list includes:
    - Each contributor’s name.
    - The list updates dynamically as contributors are added to the project.

**Comment by VeronikaHordus** [comment]
Looks good to me 👍
