### ISSUE TITLE
feat: Add instructions on how to setup analytics

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#343]
### What feature?

- [x] Add instructions on how to setup analytics to the Setup Analytics modal.
- [x] Api key and user id in the script should be pre-populated with the current values.
- [x] There should be a copy button in the script field.

The instructions should be as follows, but adjustments are allowed.

---

#### Overview

This script operates continuously in the background, collecting statistics and updating analytics data every 3 hours.

#### Api key

// api key field goes here

#### Prerequisites

- **Git:** Ensure Git is installed for repository management.
- **Node.js 20:** The script requires Node.js 20 to be installed on your machine.

#### Installation Steps

1. **Clone your project repository.**
  Use Git to clone your project repository to your local machine.
2. **Prepare the script.**
  Copy the command below and modify <project-path> with your local repository's path:
   ```bash
   npx @git-fit/analytics@latest track <apiKey> <userId> <project-path>
   ```
3. **Execute the script.**
  Open your terminal or console, paste and run the modified script.

---

**Comment by VeronikaHordus** [comment]
User Story :
As a User setting up analytics, I want to see clear instructions within the "Setup Analytics" modal, so that I can easily understand and complete the setup process without confusion.

Acceptance criteria: 

- The instructions should be clear, concise, and written in user-friendly language.
- The instructions should be dusplayed under the Header of the Setup Analytics modal.
- The texts alignment on the window should be in width.

**Comment by perekotypole** [comment]
@liza-veis  Sorry, I'm not clear on what needs to be done. I need more information.
1. What kind of information should be displayed under the heading in the modal window? Is it something brief or is all the information provided in the ticket description (Overview, Prerequisites, Installation Steps)?
2. What exactly should be specified in the script? apiKey and userId separated by a space or something else?


![Image](https://github.com/user-attachments/assets/5658f340-40ad-42eb-8e11-c7fcaca2ba8b)

**Comment by liza-veis** [comment]
> 1. What kind of information should be displayed under the heading in the modal window? Is it something brief or is all the information provided in the ticket description (Overview, Prerequisites, Installation Steps)?

all information provided above, the same format as it's currently displayed in the issue, with titles, bullet lists etc.

> 2. What exactly should be specified in the script? apiKey and userId separated by a space or something else?

the script is the code snippet from the issue description, apiKey, and userId should be replaced with actual values, and `<project-path>` should stay as it is as placeholder, no other parameters are needed.

```
npx @git-fit/analytics@latest track <apiKey> <userId> <project-path>
```

**Comment by VeronikaHordus** [comment]
@perekotypole  Seems fine to me. 
Maybe we could get rid of extra spacing between some parts to keep it unscrollable + adjust spacing between Script description and the script field, but this is a very trivial moment. Or would you like to keep it for now and see if it's okay on demo?
https://github.com/user-attachments/assets/a246f0fc-b49e-4e80-99fa-d963396646bd

**Comment by perekotypole** [comment]
@VeronikaHordus What do you think about doing this? (need to add one more line to the styles)
![image](https://github.com/user-attachments/assets/9f68f1bb-9f01-450a-96c4-4ed0f448232b)

**Comment by VeronikaHordus** [comment]
Sorry, sent a wrong image 
https://github.com/user-attachments/assets/070953ee-60e0-417e-beeb-3dcfca301e9a

**Comment by perekotypole** [comment]
@VeronikaHordus 
fixed spaces (height 663px):
![Image](https://github.com/user-attachments/assets/c5392d52-5a32-46a3-bf44-f6f4f8aacd78)

+ smaller text: font size -14px (height 612px):
![Image](https://github.com/user-attachments/assets/90a7c39c-e4c9-4e4d-8c37-fe4105da94c9)

**Comment by VeronikaHordus** [comment]
@perekotypole I think the last one is fine . I saw the @s1rserg is working on it, maybe he can adjust stiled a bit then in his PR

**Comment by VeronikaHordus** [comment]
The rest is fine!
