### ISSUE TITLE
feat: Add last activity time to contributors on project details page

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#347]
### What feature?

- [x] Add last activity date to contributors on project details page.
- [x] This label should show a relative date of the last activity log with more than zero commits. We don't track commit time, so instead of minutes we will display it as date units, e.g. Last activity today.

Time limits for the indicators are the following:
  - Green: < 2 days
  - Yellow: < 5 days
  - Red: >= 5 days

### Screenshots

![Screenshot 2024-09-16 at 22 21 15](https://github.com/user-attachments/assets/46661de2-175f-4e8b-bc95-3f534f850e6d)

**Comment by VeronikaHordus** [comment]
User Story:
As a manager I want to see when the contributors of the certain project have shown their last activity , so I can keep track on their activity throughout the day to understand whether they are at work or not.

Acceptance criteria:

- The Green indicator is shown in front of the last activity time informarion when the last commit was done < 2 days ago, a Yellow color indicator for activities <5 days ago, and a Red one for >=5 days
- The activity time is shown for each project's contributoron the right sige of the Name 
- The indicators can change their color without the page reload when the new activity have appeared or time crossed the time limit of the certain color. (dinamicly)

**Comment by VeronikaHordus** [comment]
Looks nice, thank you!
