### ISSUE TITLE
feat: Adjust root permissions

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#350]
### What feature?

Adjust needed permissions and make sure all of them work as expected. The resources should be disabled on the backend as well.

Rules:

- [x] Projects page (sidebar and page itself): View All Projects, Manage All Projects.
- [x] Analytics page (sidebar and page itself): View All Projects, Manage All Projects.
- [x] Contributors page (sidebar and page itself): Manage All Projects.
- [x] Root access management page (sidebar and page itself): Manage Access.
- [x] Project access management page (button and page itself): Manage Access.
- [x] User groups and project groups (create, edit, delete): Manage Access.
- [x] Create a new project (button):  Manage All Projects.
- [x] Delete a project (option): Manage All Project.
- [x] Edit project (option): Manage All Project.
- [x] Setup analytics button and api key generation: Manage All Projects.

**Comment by GvoFor** [comment]
## Questions
- If rule states "...: View All Projects, Manage All Projects.", then this means that user shoud have AT LEAST one of the listed permissions, right? (or all of them?)
- If there is nothing left to display in the menu (for example user has only `View All Projects` permission and not `Manage All Projects`, then both `edit` and `delete` options should disapear), then I should not render the menu component (button with ellipsis) itself at all, right?
- In rules list, `Manage Access` permission was mentioned, but currently in project we have `Manage User Access`. Are these the same permissions? or should I create new `Manage Access` permission? or should I rename `Manage User Access` to `Manage Access`?
- Our project details page contains contributors list and it can be accessed with just `View All Projects` permission, but `Contributors` page can be accessed only with `Manage All Projects` permission. So should I render contributors list in this case?

**Comment by liza-veis** [comment]
> If rule states "...: View All Projects, Manage All Projects.", then this means that user shoud have AT LEAST one of the listed permissions, right? (or all of them?)

yes, one of them.

> If there is nothing left to display in the menu (for example user has only View All Projects permission and not Manage All Projects, then both edit and delete options should disapear), then I should not render the menu component (button with ellipsis) itself at all, right?

yes, would be nice to hide the options menu.

>In rules list, Manage Access permission was mentioned, but currently in project we have Manage User Access. Are these the same permissions? or should I create new Manage Access permission? or should I rename Manage User Access to Manage Access?

yep, It's the sam permission, no need to rename or create a new one.

> Our project details page contains contributors list and it can be accessed with just View All Projects permission, but Contributors page can be accessed only with Manage All Projects permission. So should I render contributors list in this case?

Contributors page will be for all contributors configuration, so only users with Manage All Projects (who is able to edit contributors) can access it. It will be hard to show all contributors, but disable actions for some of them if user has/doesn't have project-specific permissions. But it's ok for the project details page, + contributors on this page are mostly for view and tracking purposes, so users with View All Projects permission should see them.

**Comment by VeronikaHordus** [comment]
@GvoFor Everything seem to work as required, only I have one point to make clear. The Project Access Managment page is unaccessible for user with Manage Access rights untill he has also the View All Projects permission. (If I wold paste the URL of the Project Access Managment page I am redirected to the 404 page). 
Is that right?

**Comment by GvoFor** [comment]
Hi. Thanks for noticeing. Looks like a bug for me. I will ask about this on daily and fix it if needed

**Comment by GvoFor** [comment]
@VeronikaHordus Hello. I have fixed the issue. Now the Project Access Management page available only if user has Manage User Access permission AND either View or Manage All Projects

**Comment by VeronikaHordus** [comment]
Thank you, Will check it today 👍 

> @VeronikaHordus Hello. I have fixed the issue. Now the Project Access Management page available only if user has Manage User Access permission AND either View or Manage All Projects

**Comment by VeronikaHordus** [comment]
@GvoFor  I have 2 bugs here. So I will return the ticket in ToDo :(

1. The options button Contributors on the Project Details page is availible to "View All Projects" users. 
(They shouldn't see Options button as well as Edit or Merge them, this is availible only for Manage All Projects permission type)
https://github.com/user-attachments/assets/aa04d1a5-04c2-48d0-8eb3-9dfa6ecd2303

**Comment by GvoFor** [comment]
Thanks for noticing! New functionality was added and I didn't adjust right permissions for it. I'll fix it as soon as possible

**Comment by GvoFor** [comment]
@VeronikaHordus  Hi again. I'm confused with the second bug you described. It's a bit contrudict with https://github.com/BinaryStudioAcademy/bsa-2024-gitfit/issues/411 ticket and @liza-veis [suggestion](https://bsa2024.slack.com/archives/C07HWM8616U/p1726738432492769?thread_ts=1726730256.980859&cid=C07HWM8616U). Could you clarify with @AnnaRomaniuta and @liza-veis what should be expected behaviour, please

**Comment by AnnaRomaniuta** [comment]
@GvoFor I had this  [ticket](https://github.com/orgs/BinaryStudioAcademy/projects/28/views/1?pane=issue&itemId=79242819) and it was indicated here that this access should be available.

**Comment by GvoFor** [comment]
Do I understand correctly?:
- Root Access Management page available only with `Manage User Access`
- Project Access Management page available in two cases:
  1) User has `Manage User Access` and `View All Projects` permissions
  2) User has `Manage All Projects` permission

**Comment by AnnaRomaniuta** [comment]
Yesterday, the user with **Manage User Access** didn't have access to the project, instead the user with **Manage All Projects** permission had all rights to create projects and groups. But today everything seems to have changed, I also want to know the final solution from @liza-veis because I am also confused.

**Comment by liza-veis** [comment]
> Do I understand correctly?:
> 
> * Root Access Management page available only with `Manage User Access`
> * Project Access Management page available in two cases:
>   
>   1. User has `Manage User Access` and `View All Projects` permissions
>   2. User has `Manage All Projects` permission

yes, this is correct, can look a bit strange, but this is because we have a small set of permissions. Usually, the user has permission for each separate operation.

**Comment by VeronikaHordus** [comment]
Oh okay, sorry @GvoFor then perhaps I got it wrong from the conversation in the chat. Let’s then keep it for Manage All Project available

**Comment by VeronikaHordus** [comment]
Works good, thank you!
The only issue is the unability to update personal profile, but this one is already in proccess
