### ISSUE TITLE
feat: Adjust project permissions

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#351]
### What feature?

- [x] Add "Edit Project" and "Manage Project" project permissions.

Users with appropriate project permissions should be able to access some resources even without root permissions. Adjust needed project permissions and make sure all of them work as expected. All permissions enable functionality only for specific projects. The permissions should be updated on the backend as well. It shouldn't change something in root permissions #350 and root permissions are considered first. 

Rules:

- [x] Projects page (sidebar and page itself): View Project,  Edit Project, Manage Project. If user doesn't have root permissions, only projects enabled for user by project groups should be shown.
- [x] Analytics page (sidebar and page itself): View Project,  Edit Project, Manage Project. If user doesn't have root permissions, only projects enabled for user by project groups should be shown.
- [x] Project Access Management (button and page itself): Manage Project.
- [x] Project groups (create, edit, delete): Manage Project.
- [x] Edit project (option): Edit Project, Manage Project.
- [x] Setup analytics button and api key generation: Edit Project, Manage Project.

**Comment by VeronikaHordus** [comment]
There are quite bugs, I will retest this ticket after all bugs are fixed cuz they might influence one another !

**Comment by VeronikaHordus** [comment]
Seems to be good now, thank you!
