### ISSUE TITLE
feat: Fix quality criteria issues

### ISSUE THREAD

**Issue by what1s1ove** [BinaryStudioAcademy/bsa-2024-gitfit#382]
### What feature?

<img width="547" alt="image" src="https://github.com/user-attachments/assets/d0fb2fbe-4c10-4991-a3d9-65808a0fd240">

<img width="547" alt="image" src="https://github.com/user-attachments/assets/9e062ae6-b391-4343-b8dd-5fca9556e27b">

**Comment by Vitaliistf** [comment]
Thanks! I've changed it. What should I do next? Should I reopen the PR, or create another one?

**Comment by GvoFor** [comment]
Since your PR was merged, I think you should create new branch `382-fix-...` , then commit the changes on this branch and then open new PR

**Comment by GvoFor** [comment]
@Vitaliistf you missed a couple of helpers. Here they are
- apps/frontend/src/libs/hooks/use-pagination/libs/helpers
- apps/backend/src/libs/plugins/authorization/helpers
- apps/frontend/src/pages/access-management/libs/components/group-form/libs/helpers
- apps/frontend/src/pages/project-access-management/libs/components/project-group-form/libs/helpers

**Comment by GvoFor** [comment]
@Vitaliistf Looks good to me. Thanks!
