### ISSUE TITLE
feat: Add sign-in flow

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#4]
### What feature?

- [x] Add `/sign-in` route
- [x] Add sign-in form
- [x] Add sign-in action flow
- [x] After form submission, the user is redirected to the app `/`
- [x] Save an authenticated user to the redux store
- [x] Add form validation (shared)
- [x] Implement design
- [x] "Create new" link should navigate to the sign-up page

### Screenshots

![Sign in](https://github.com/user-attachments/assets/8ae24691-5a88-4a13-96c2-e3b5ea0c6b9d)

**Comment by AnnaRomaniuta** [comment]
Looks good, thanks!
