### ISSUE TITLE
feat: Add users column to groups table on project access management page

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#403]
### What feature?

- [x] Add users column to groups table on project access management page. (Same as for root access management)

### Screenshots

![Image](https://github.com/user-attachments/assets/667af110-e183-43bf-ba30-b072e069cdbe)

**Comment by kolibri753** [comment]
BUG FIX: After creating a new group on project-access-management, the group only appeared in the groups table, not in the users table. Updated to ensure users table refreshes correctly with newly created groups.

**Comment by AnnaRomaniuta** [comment]
Looks good!
