### ISSUE TITLE
feat: Update analytics instructions with the new flow

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#406]
### What feature?

- [x] Update the instruction to match pm2 requirements.
- [x] Simplify the blocks, maybe we can reduce the info or put something into one sentence so that it doesn't look too large.

**Comment by s1rserg** [comment]
@liza-veis That's what I was able to figure out. I'd appreciate your feedback.
![image](https://github.com/user-attachments/assets/794e9d2f-b6e3-40ec-b943-801eb90abaa9)

Also, I wanted to let you know that the QA team attempted to test the script, but it seems that the git-fit/shared package isn't available on npm yet. To avoid any confusion, I’ve moved the tickets to the "In Code Review" column. It would be great if you could inform the team when everything will be published that it's ready for testing.

**Comment by liza-veis** [comment]
Regarding the instruction, we should merge installation steps with restart on reboot steps, because this will be the default flow and currently it looks a bit confusing.

> To avoid any confusion, I’ve moved the tickets to the "In Code Review" column. It would be great if you could inform the team when everything will be published that it's ready for testing.

Good, thanks for letting me know

**Comment by VeronikaHordus** [comment]
Looks good to me!
