### ISSUE TITLE
feat: Add users table

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#41]
### What feature?

- [x] Add access management item to the sidebar #12, which should lead to `/access-management` route
- [x] Add common page layout
- [x] Add users table to the page. For now, it should have only "Name" and "Created At" columns
- [x] Data should be taken from the current users table on the backend

### Screenshots

![Image](https://github.com/user-attachments/assets/c8016e24-ba6f-4cc3-a9ef-2b8822a0f46c)

**Comment by VeronikaHordus** [comment]
Good job <3
