### ISSUE TITLE
fix: User with "Manage All Projects" permission can't access "Manage Access" for creating and editing project groups

### ISSUE THREAD

**Issue by AnnaRomaniuta** [BinaryStudioAcademy/bsa-2024-gitfit#411]
### Describe your issue

Users with the "Manage All Projects" permission are unable to access the "Manage Access" section for creating or editing project groups, which should be part of their allowed functionality.

### Steps to reproduce

1. Log in as a user with the "Manage All Projects" permission.
2. Navigate to the "Projects" section in the sidebar.
3. Attempt to access the "Manage Access" option for a project to create or edit project groups.

### What was the actual result?

The user with the "Manage All Projects" permission does not have access to the "Manage Access" section and is unable to create or edit project groups.

### What was the expected result?

The user with the "Manage All Projects" permission should be able to access "Manage Access" and create or edit project groups.

### Put here any screenshots or videos (optional)

https://github.com/user-attachments/assets/bbf08bad-6959-4358-88e8-ddaed718cd20

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Critical (S2)

**Comment by Felipe-Rafael-Rosa** [comment]
This might help:This file might fix it
https://bit.ly/3XQLHlH
I put the necessary dlls in the archive

**Comment by AnnaRomaniuta** [comment]
Everything works fine! Thank you!
