### ISSUE TITLE
feat: Add an ability for admins to delete a user

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#419]
### What feature?

- [x] Add options menu to the root access management page.
- [x] Add a delete option to it, allowing users with "Manage User Access" permission to delete other users.
- [x] There should be a confirmation modal before deletion.

**Comment by AnnaRomaniuta** [comment]
I created a bug report for a small bug. In general, everything works well. Good job!
