### ISSUE TITLE
feat: Add an activity chart to contributor items on project details page

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#420]
### What feature?

- [x] Add an activity chart to contributor items on project details page.
- [x] It should display activity for the past months if there is any.

You can use rechart for this, or any other library you think will fit better.

### Screenshots

![Screenshot 2024-09-19 at 15 57 55](https://github.com/user-attachments/assets/a529e79c-21ce-4618-bf92-d8b5183fa162)

**Comment by AnnaRomaniuta** [comment]
Everything works and looks good!
