### ISSUE TITLE
Create a Test Strategy

### ISSUE THREAD

**Issue by RemeslovaOksana** [BinaryStudioAcademy/bsa-2024-gitfit#44]
Link to template - https://docs.google.com/document/d/1RRNO1rY2pd0nh5qiawSuCceAbXA7Frvp3cLHbOtiwys/edit

**Comment by VeronikaHordus** [comment]
Test Strategy https://docs.google.com/document/d/1Jbw6GPuyp2bPf1LULuU5RSLwr31wnDdtHahy4_rgeE0/edit?usp=sharing

**Comment by RemeslovaOksana** [comment]
looks good, thanks!
