### ISSUE TITLE
fix: Inconsistent Users table resolution on the Access managment page on 1440px screen resolution

### ISSUE THREAD

**Issue by VeronikaHordus** [BinaryStudioAcademy/bsa-2024-gitfit#448]
### Describe your issue

The Users table is not shown fully on the page, the horizontal scrollbar appears.

### Steps to reproduce

Pre-conditions: User is logged in. User have "Manage User Access" permission

1. Open the Access Managment page
2. Observe the page tables appearance with 1440px screen resolution

### What was the actual result?

The Users table is not fully displayed on the page. The horizontal scroll is shown.

### What was the expected result?

The Users table is fully displayed in width for the Access Managment page with 1440px screen resolution.

### Put here any screenshots or videos (optional)

![Image](https://github.com/user-attachments/assets/f7b2fa9b-a573-4d3a-ace7-c61a2afb9b17)

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Major (S3)

**Comment by VeronikaHordus** [comment]
@GvoFor I see that the same issue but less noticible appearse on the Project Access Managment. Shall I make a new ticket for it or maybe You can try fix it in the current one?

**Comment by GvoFor** [comment]
No need for new ticket. I'll fix it in scope of this ticket

**Comment by VeronikaHordus** [comment]
Looks good !
