### ISSUE TITLE
fix: User profile not deleted without "Manage User Access" permission

### ISSUE THREAD

**Issue by AnnaRomaniuta** [BinaryStudioAcademy/bsa-2024-gitfit#449]
### Describe your issue

Only a user with "Manage User Access" permission can delete an account. Users are expected to be able to delete their account regardless of permission.

### Steps to reproduce

1. Log in with a user account that doesn't have the Manage User Access permission.
2. Navigate to the Profile page.
3. Select the option to Delete Account.
4. Confirm account deletion.
5. Attempt to log in again using the same credentials.

### What was the actual result?

The account has been deleted, but the user can still log in after deletion, indicating that the profile has not been completely deleted.

### What was the expected result?

Users with all permissions should be able to permanently delete their account.

### Put here any screenshots or videos (optional)

https://github.com/user-attachments/assets/48627da7-e121-4eb6-ad6c-64ea7a9bbd35

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Critical (S2)

**Comment by VeronikaHordus** [comment]
@Vitaliistf  i found one more point, I think this connected with the profile deletion as well, so maybe convinient to fix them at once.

Users without "Manage User Access" permission cannot update the profile information. (Same as user with no permission at all cannot update their personal profile)

https://github.com/user-attachments/assets/48f500b4-a9c8-433f-bd3d-10ef7b1e6fa5

**Comment by Vitaliistf** [comment]
Yeah, I think I'll fix them at once. This wouldn't require any additional work.
