### ISSUE TITLE
Create a Test Plan

### ISSUE THREAD

**Issue by RemeslovaOksana** [BinaryStudioAcademy/bsa-2024-gitfit#45]

**Comment by AnnaRomaniuta** [comment]
An introductory part has been created.

**Comment by AnnaRomaniuta** [comment]
A description of the scope of testing in the Test Plan has been created.

**Comment by VeronikaHordus** [comment]
Add out of scope and  test criteria section in the Test Plan.

**Comment by AnnaRomaniuta** [comment]
Add test strategy and approach section in the Test Plan.

**Comment by VeronikaHordus** [comment]
Add resorses section with human resourses listed and schedule, enviroments and tools , described types of documentation that are used within the project, add metrics to evaluate the testing result

**Comment by VeronikaHordus** [comment]
Corrected recommendations and reformated the document.
