### ISSUE TITLE
fix: A double reload occurs after closing and reopening the group creation modal after sorting in the search field

### ISSUE THREAD

**Issue by AnnaRomaniuta** [BinaryStudioAcademy/bsa-2024-gitfit#455]
### Describe your issue

After closing the group creation modal window and reopening it, a double reload occurs. This happens specifically after using the search field to sort users. 

### Steps to reproduce

1. Navigate to the Access Management or Project Manage Access page.
2. Click on the "Create New" group button.
3. Enter text into the search field to filter users.
4. Close the modal window without saving.
5. Reopen the group creation modal by clicking the "Create New" group button again.

### What was the actual result?

When reopening the group creation modal after performing sorting in the search field, a double reload (two loading events).

### What was the expected result?

The modal should reopen without any double reloads, and the sorting functionality in the search field should not trigger unnecessary loading events.

### Put here any screenshots or videos (optional)

https://github.com/user-attachments/assets/458f37bb-eea3-4530-8eb4-a402ec3d52f9

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Major (S3)

**Comment by AnnaRomaniuta** [comment]
@Fjortis Everything works fine in the groups table on the Access Management page. Maybe it's my fault that I didn't point it out right away, but we have the same problem on the projects page when we create a group of projects.

**Comment by Fjortis** [comment]
@Fjortis I will adjust that as well, it is obvious that wouldn't work either. And oversight from me

**Comment by AnnaRomaniuta** [comment]
@Fjortis Are you going to fix it based on this ticket or do you need to create a new one?

**Comment by Fjortis** [comment]
I will fix it based on this one, it is the same issue

**Comment by AnnaRomaniuta** [comment]
Looks good!
