### ISSUE TITLE
feat: Add infinite scroll to notifications

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#458]
### What feature?

- [x] Add infinite scroll to user notification popup.
- [x] Load only the first 10-15 notifications.

### Screenshots

![Image](https://github.com/user-attachments/assets/661f8bbd-3ef7-4890-80c3-786bc94e0e69)

**Comment by VeronikaHordus** [comment]
Got a small bug, not related with the scroll directly. Scroll looks good 👍
