### ISSUE TITLE
feat: Add an ability to mark notifications as read

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#460]
### What feature?

- [x] And unread notifications count badge to the notifications icon.
- [x] When user opens notifications popup, unread notifications should have an effect we currently have on hover. Remove this hover effect on notifications (notifications are not clickable for now).
- [x] When a user opens popup we need to mark notifications as read, but the user will only see this when he opens the popup again. So on the initial render, a user should be able to see which notifications are unread. 

Notes:
Don't add mark all as read as on the screenshot.

### Screenshots

![Image](https://github.com/user-attachments/assets/bd3ef1ae-5a77-4b51-8da5-046c05c03a81)

**Comment by AnnaRomaniuta** [comment]
Looks good!
