### ISSUE TITLE
feat: Add an ability to split contributors

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#462]
### What feature?

- [x] Add a split option to the contributors table.
- [x] This option should be shown only for contributors with more than one git email. We cannot split contributors with one git email, this check should be on the backend side too.
- [x] When the option is clicked a modal should be opened. It should display:
  - Current contributor name and emails split by coma, this input is disabled (same as for merge contributors).
  - A select field with current contributor emails (this is the email we will detach and transfer to a new contributor).
  - New contributor name field, should be prefilled with the current contributor name by default.
- [x] When the form is submitted, a new contributor should be created and the selected email should be transferred to this contributor.
- [x] Update warning in the merge contributors modal. Instead of "This action cannot be undone" it should now say "This action can be undone later using the split functionality."

### Screenshots

![Image](https://github.com/user-attachments/assets/6145d6a1-0ac9-4cee-80f8-6848d401e1b8)
![Image](https://github.com/user-attachments/assets/df690d73-6221-452c-a316-5ca2c9d9338e)

**Comment by VeronikaHordus** [comment]
Found one bug, but mainly everything is good.
A new ticket created for the bug
