### ISSUE TITLE
fix: The total number of users is not updated in the groups table after deleting a user

### ISSUE THREAD

**Issue by AnnaRomaniuta** [BinaryStudioAcademy/bsa-2024-gitfit#463]
### Describe your issue

When a user with "Manage User Access" permission deletes another user who was part of a user group, the user is successfully deleted, but the total user count in the group does not update to reflect the removal.

### Steps to reproduce

1. Log in as a user with "Manage User Access" permission.
2. Navigate to the root access management page.
3. Add a user to a group.
4. Delete the user who was previously added to the group.
5. Observe the user count in the "Users" column of the group.

### What was the actual result?

The user added to the group is removed from the system, but the total number of users in the group remains unchanged.

### What was the expected result?

The total number of users in the Users column in the groups table should decrease by one after the user is removed from the system.

### Put here any screenshots or videos (optional)

https://github.com/user-attachments/assets/af9f1335-7d51-4fd0-b780-b3609b74f14d

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Minor (S4)

**Comment by AnnaRomaniuta** [comment]
@Vitaliistf The situation is the same with the table of project groups.

**Comment by VeronikaHordus** [comment]
Looks good now
