### ISSUE TITLE
fix: The loader component is not vertically centralized on the Analytics page 

### ISSUE THREAD

**Issue by VeronikaHordus** [BinaryStudioAcademy/bsa-2024-gitfit#471]
### Describe your issue

When open the Analytics page a page loader is placed at the top of the page istead of the middle point of the page.

### Steps to reproduce

Pre-conditions: User is logged in. User is granted with "View All Projects" or "Manage All Projects" permission.
The Projects page is open.
1. Open the Devtools and setup the low-internet connection (for better visiability)
2. Navigate to the Analytics page using a link on a sidebar
3. Observe how the loader is placed on the page.

### What was the actual result?

The loader placed at the top of the Analytics page.

### What was the expected result?

The loader is centralised horizontally and vertically on the page.

### Put here any screenshots or videos (optional)

![Image](https://github.com/user-attachments/assets/ad288f6e-543a-4a4a-9f76-486cc2514dd9)

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Minor (S4)

**Comment by AnnaRomaniuta** [comment]
Looks good!
