### ISSUE TITLE
fix: The submission button for the Create Project Group modal has inconsistent to the mockup text

### ISSUE THREAD

**Issue by VeronikaHordus** [BinaryStudioAcademy/bsa-2024-gitfit#474]
### Describe your issue

The submission button on the Create Project Group modal text is "Submit" instead of the required "Create"

### Steps to reproduce

Pre-conditions: User is logged in. User is granted with "View All Projects" and "Manage User Access" permission.
The Projects page is open.

1. Navigate to the Projects Details page
2. Click on the Oprions (3 dots) button and navigate to the Manage Access Page 
3. Click on the Create button on the right top corner of the Groups table
4. Observe the test on the submission button of the modal

### What was the actual result?

The "Submit" button is displayed to sibmit the form.

### What was the expected result?

The "Create" button is displayed to sibmit the form.

### Put here any screenshots or videos (optional)

https://github.com/user-attachments/assets/123ef212-358c-4f35-bce3-53bece41fdac

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Trivial (S5)

**Comment by perekotypole** [comment]
@VeronikaHordus I have changed the button label in the Update form as well, ok?

**Comment by VeronikaHordus** [comment]
Sure, this is perfect, thank you!

**Comment by VeronikaHordus** [comment]
Looks good, thanks!
