### ISSUE TITLE
feat: Add sign-up flow

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#5]
### What feature?

- [x] Add `/sign-up` route
- [x] Add sign-up form
- [x] Add sign-up action flow
- [x] After form submission, the user is redirected to the app `/`
- [x] Save an authenticated user to the redux store
- [x] Add form validation (shared)
- [x] Implement design
- [x] "Log in" link should navigate to the sign-in page

### Screenshots

![Sign up](https://github.com/user-attachments/assets/1269c4a9-27a0-4fd8-b368-75e869b8de52)

**Comment by VeronikaHordus** [comment]
Added updates as a Feature request. The rest is good, thanks!
