### ISSUE TITLE
feat: Add analytics last sync time to project details page

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#502]
### What feature?

- [x] When the analytics is set up (at least one log item or contributor), remove the setup analytics button from ui.
- [x] Near the Contributors title, display the last update time and the user by whom analytics was uploaded. This will be the time the last analytics log is created and the user by whom it was created.
- [x] When the last update was more than 5 hours ago,  the label with sync time and user should be red, and on hover, there should be a tooltip saying: Analytics have not been uploaded for over 5 hours. There may be an issue, and you might need to set it up again.

### Screenshots

![Image](https://github.com/user-attachments/assets/63754fd9-a5ac-4d97-9db5-09a16be6e31e)

**Comment by AnutkaGn** [comment]
I want to ask clarifying questions to make sure I understand correctly.
1. I need to create an endpoint on the backend in order to get the user by whom analytics was uploaded (the created_by_user_id, date field should be taken from the log activity table)
2. There is a reload button on the frontend, as I understood when clicking on this button we make a request to the backend to receive the latest information (when and who updated)

**Comment by liza-veis** [comment]
> 1. I need to create an endpoint on the backend in order to get the user by whom analytics was uploaded (the created_by_user_id, date field should be taken from the log activity table)

you can return this with project details.

> 2. There is a reload button on the frontend, as I understood when clicking on this button we make a request to the backend to receive the latest information (when and who updated)

it's not a reload button, it's just an icon to show that this is synchronization status.

Also forgot to mention this in the ticket, with hiding Setup Analytics button we also need to display `Setup Again` button which will do the same as `Setup Analytics` button, and should only be available with the same permissions needed for Setup Analytics button

**Comment by AnnaRomaniuta** [comment]
Good job!
