### ISSUE TITLE
feat: Decrease the default Date range for the Analytics page to 1 week

### ISSUE THREAD

**Issue by VeronikaHordus** [BinaryStudioAcademy/bsa-2024-gitfit#503]
### What feature?

As a Project manager in the Agile based work environment I want to see the latest project updated and track contributors activity based on a short term data, so that I can easily influence on the low activity results.

- The default Analytics date rande is 1 week 

### Screenshots

![Image](https://github.com/user-attachments/assets/b33dfddc-32a2-4b65-9679-e8e7b4eeed29)

**Comment by AnnaRomaniuta** [comment]
Looks good!
