### ISSUE TITLE
fix: Inconsistent data display for same date range on Analytics Page

### ISSUE THREAD

**Issue by AnnaRomaniuta** [BinaryStudioAcademy/bsa-2024-gitfit#510]
### Describe your issue

When selecting the same date range on the Analytics page, different results are displayed. For example, upon initially opening the page with the date range 25.08.2024 - 24.09.2024, commits are shown for the 18th, 20th, and 23rd of September, but no commits are shown for the 24th of September. However, when selecting a slightly adjusted date range, such as 28.08.2024 - 24.09.2024, no commits are displayed for the 23rd of September, but commits appear for the 19th, 21st, and 24th of September. This happens with different ranges of values.

### Steps to reproduce

1. Navigate to the Analytics page.
2. Select the date range from 25.08.2024 to 24.09.2024.
3. Observe the displayed commits.
4. Change the date range to 28.08.2024 to 24.09.2024.
5. Compare the commits displayed for the same days (23rd and 24th of September) across the two different ranges.

### What was the actual result?

Different commits are shown for the same dates depending on the date range selected.

### What was the expected result?

The same commits should be displayed consistently for the same date range, regardless of slight adjustments in the range's start date.

### Put here any screenshots or videos (optional)

https://github.com/user-attachments/assets/62c41dfc-d60e-465d-bf2e-96e43ab1d319

![Image](https://github.com/user-attachments/assets/51e084db-7b47-4db2-9627-4facaeaed660)
![Image](https://github.com/user-attachments/assets/4ff59ef5-8beb-4f4f-8df0-31a4052e43a7)

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Critical (S2)

**Comment by sandrvvu** [comment]
@liza-veis I think I found the problem. In the backend, it was searching by date including the time, which is why some logs were not displaying. Additionally, the frontend was also sending the dates in ISO format with the time included. 
I'll take this one, if you don't mind.

**Comment by AnnaRomaniuta** [comment]
Everything is working fine now!
