### ISSUE TITLE
fix: The "There is noting yet." message displayed in the notifications popover when the data is still loading

### ISSUE THREAD

**Issue by VeronikaHordus** [BinaryStudioAcademy/bsa-2024-gitfit#515]
### Describe your issue

When the internet connection is low the "There is nothing yet" massage shown for notifications popover.

### Steps to reproduce

Pre-conditions: User have notification in the notification popover. User logged in.

1. Simulate the low-internet connection (3G) using devTools
2. Open any page of the application
3. Click on the Notifications icon in the popover
4. Observe how the popover looks when the data is in the proccess of loading.

### What was the actual result?

The "There is nothing yet" message shown for the popover. 

### What was the expected result?

The loader is shown in the popover when the data is not loaded yet.

### Put here any screenshots or videos (optional)

https://github.com/user-attachments/assets/3b689d82-7ffa-4eac-b93c-4d903bae3603

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Minor(S4)

**Comment by AnnaRomaniuta** [comment]
Everything looks good now!
