### ISSUE TITLE
feat: Add validation notification for incorrect password on login

### ISSUE THREAD

**Issue by AnnaRomaniuta** [BinaryStudioAcademy/bsa-2024-gitfit#517]
### What feature?

- [x] When a user enters an incorrect password, there should be a clear and visible notification indicating the error (for example, "Incorrect password. Please try again.").

- [x] A notification should appear immediately after a failed login attempt.

- [x] The notification style should be consistent with other error messages in the application (for example, use the same color, font, and layout).

### Screenshots

https://github.com/user-attachments/assets/5297b179-a67b-40ae-937f-ad75ccc476c3

Currently, if a user inputs an invalid password while trying to log in, there is no immediate feedback. This can cause confusion, as the user might think that the application is stuck or not responding.

**Comment by Fjortis** [comment]
@AnnaRomaniuta 

I started to fix this, but i just realized what was said on a Demo about exposing user information, perhaps we handle it the same way as email? Invalid credentials? Because if i can see incorrect password, then i can find someone's email.

**Comment by AnnaRomaniuta** [comment]
@Fjortis Good point. It’s a great idea to implement this the same way as we do for an incorrect email address.

**Comment by AnnaRomaniuta** [comment]
Everything looks good now.
