### ISSUE TITLE
fix: Double reload occurs befor the matching search criteria results are displayed on the Analytics page

### ISSUE THREAD

**Issue by VeronikaHordus** [BinaryStudioAcademy/bsa-2024-gitfit#529]
### Describe your issue

When enter data into the search field the Analytics table reloads 2 times before the matching search results are shown

### Steps to reproduce

Pre-conditions: User is logged in. User have "View All Projects" or "Manage All Projects"permission.

1. Open the Analytics page
2. Inject 1 character into the search field
3. Observe the Analytics table behaviour

### What was the actual result?

A double reload occur before the correct search result are displayed. The correct results are shown after the second reload.

### What was the expected result?

The Analytics table updades dinamically with each single letter injected into the Search field. One character injection triggers one table reload to update data and find matching the search result

### Put here any screenshots or videos (optional)

1. https://github.com/user-attachments/assets/63600ae6-057b-464d-b779-7abf5c60a1ba
2.  With slow internet connection (slow 4G)
https://github.com/user-attachments/assets/42f804d2-f924-4686-ad1b-62422881ed13

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Major (S3)

**Comment by AnnaRomaniuta** [comment]
Looks good!
