### ISSUE TITLE
feat: Add an ability to create a group

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#53]
### What feature?

- [ ] Add `permissions` table (columns: id, key, name, created_at, updated_at). Limit the name to 100 chars.
- [ ] Add `user_groups` table (columns: id, key, name, created_at, updated_at). Limit the name to 100 chars.
- [ ] Add `users_to_user_groups` table (columns: id, user_group_id, user_id, created_at, updated_at).
- [ ] Add `user_groups_to_permissions` table (columns: id, user_group_id, permission_id, created_at, updated_at).
- [ ] Add `manage_user_access` permission (name: "Manage User Access") through migration.
- [ ] Add needed models, and services on the backend.
- [ ] Add a controller for groups with `POST /groups` route
- [ ] The payload for group creation should contain name, user_ids, and permission_ids. Using this payload you will need to create an item in `user_groups`, then items in `user_groups_to_permissions` and then in `users_to_user_groups`. 
- [ ] The key should be automatically generated in the service by turning name into snake_case.
- [ ] The key should be unique for permissions and user_groups table (restriction on db level and check on backend as well)
- [ ] Update db schema in readme accordingly (rename groups table to user_groups, columns etc.)

**Comment by liza-veis** [comment]
A validation on request payload should be added too.

**Comment by VeronikaHordus** [comment]
Everythink works as ordered 👍 Thank you !
