### ISSUE TITLE
fix: Inconsistent Analytics page elements alignment for the small screen size (1024px)

### ISSUE THREAD

**Issue by VeronikaHordus** [BinaryStudioAcademy/bsa-2024-gitfit#530]
### Describe your issue

When open the Analutics page with set up 1024px screen size the page elements do not adjust to the screen size. 
( I see that the reason is an abscence of flexibility for the Search, Selector, Datapicker fields)

### Steps to reproduce

User is logged in. User is granted with "View All projects" or "Manage All Projects" permission.

1. Open the Analytics page
2. Open devtools and setup the screen resolution for 1024 px
3. Observe the page look

### What was the actual result?

The page elements cross the basic page limits and extend the page, thus the header and the sidebar have a broken look

### What was the expected result?

The page displayed properly for all screen sizes. 

### Put here any screenshots or videos (optional)

![Image](https://github.com/user-attachments/assets/ab2f748d-6c52-465c-9af5-44eaadedb66f)

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Critical (S2)

**Comment by AnnaRomaniuta** [comment]
Everything looks good to me!
