### ISSUE TITLE
feat: Order contributors list on the Project Details page by the last activity (the latest active ones on top)

### ISSUE THREAD

**Issue by VeronikaHordus** [BinaryStudioAcademy/bsa-2024-gitfit#533]
### What feature?

Place the contributors in the Contributors list on the Project Details page in order of the last activity time.
The latest active contributors should be displayed on top of the list.
The List should be sinc with last analitycs updates

### Screenshots

https://github.com/user-attachments/assets/adb0c608-dd12-4fde-a18f-551a40e07868

**Comment by AnnaRomaniuta** [comment]
@Vitaliistf Unfortunately, I don't see any changes. Please check if the changes went well.

**Comment by Vitaliistf** [comment]
> Unfortunately, I don't see any changes

Strange... Did you pull last changes from main?
It works well on my machine, and I can't see a reason why it won't work on yours if you have latest changes...

![Image](https://github.com/user-attachments/assets/9544064c-e43c-4156-9288-8a2939536301)

Regarding your question, I think it's better to ask Liza. We can do it.

**Comment by AnnaRomaniuta** [comment]
@Vitaliistf This is how it looks on stage now![Image](https://github.com/user-attachments/assets/c4b09c92-a839-47e6-b4d0-6a869a624474)

**Comment by Vitaliistf** [comment]
@AnnaRomaniuta Maybe try to update analytics?

**Comment by AnnaRomaniuta** [comment]
Everything looks good now! Good job!
