### ISSUE TITLE
fix: Browser "Back" button not functioning after redirecting to the Analytics page from the Project details page

### ISSUE THREAD

**Issue by AnnaRomaniuta** [BinaryStudioAcademy/bsa-2024-gitfit#540]
### Describe your issue

The browser's "back" button does not work after the user is redirected to the analytics page from the project details page by clicking on a contributor item.

### Steps to reproduce

1. Open the Project details page.
2. Click on any contributor item to navigate to the analytics page.
3. Try using the browser's "back" button to return to the project details page.

### What was the actual result?

The "back" button doesn't return the user from the Analytics page to the previous page (the project details page).

### What was the expected result?

The user should be able to navigate back to the Project details page by clicking the browser "back" button after being redirected to the Analytics page.

### Put here any screenshots or videos (optional)

https://github.com/user-attachments/assets/f3d90fec-22eb-40be-ac78-a5026e78a546

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Major (S3)

**Comment by s1rserg** [comment]
There are also added:
* Fix: Activity chart is also clickable and is redirecting to Analytics page & has cursor pointer.
* Feature: Contributor's name is preselected after redirecting on Analytics page.
