### ISSUE TITLE
feat: Update schema in readme to match the App

### ISSUE THREAD

**Issue by kolibri753** [BinaryStudioAcademy/bsa-2024-gitfit#543]
### What feature?

The schema in readme.md doesn't fully match what's being used in the app.

### What Changes?

- [x] Add `dateTime last_activity_date` to the `projects` table.
- [x] Modify projects name to `varchar name UK` to show uniqueness.
- [x] Add `varchar encrypted_key UK` to the project_api_keys table.
- [x] Change `activity_logs` `date` from `date` to `dateTime`.

**Comment by AnnaRomaniuta** [comment]
Good job!
