### ISSUE TITLE
feat: analytics date column alignment with table head

### ISSUE THREAD

**Issue by Fjortis** [BinaryStudioAcademy/bsa-2024-gitfit#545]
### What feature?

The analytics cells for emty "-" is not aligned with header, adjustment is needed to make it aligned.

### Screenshots

![Screenshot 2024-09-26 092706](https://github.com/user-attachments/assets/9e21b47f-0136-4b6d-8a8b-b28c41b08f2c)

**Comment by VeronikaHordus** [comment]
Nice and centralised, thank you!
