### ISSUE TITLE
fix: Incorrect time display and color coding for analytics last sync time on the project details page

### ISSUE THREAD

**Issue by AnnaRomaniuta** [BinaryStudioAcademy/bsa-2024-gitfit#547]
### Describe your issue

On the project details page, the "Last sync" label shows "24 hours ago" instead of switching to "1 day ago" once the time exceeds 23 hours. Additionally, updates that occurred more than 5 hours ago should be displayed in red, but currently, all updates beyond 5 hours, including those measured in days, are displayed in gray.

### Steps to reproduce

1. Go to the list of projects on the projects page.
2. Select a projects.
3. Check the "Last sync" mark on the project details page, next to the contributors.
4. Pay attention to the color of the messages for Last sync more than 5 hours
5. Pay attention to Last sync that were created 24 hours ago.

### What was the actual result?

1. The label displays "24 hours ago" when the last sync occurred more than 23 hours ago.
2. Updates that took place several days ago are highlighted in gray.

### What was the expected result?

1. The label should display "1 day ago" when the last sync exceeded 23 hours.
2. Updates more than 5 hours ago should be displayed in red, including days.

### Put here any screenshots or videos (optional)

![Image](https://github.com/user-attachments/assets/f03f3469-48cc-42a1-afe1-2324f94202ae)
![Image](https://github.com/user-attachments/assets/2ac6d22d-80e0-4dc7-9bd2-4419a3785b13)

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Minor (S4)

**Comment by VeronikaHordus** [comment]
Now it works as ordered, thank you!
