### ISSUE TITLE
fix: Not all contributors are displayed in contributor merge form on Contributors page

### ISSUE THREAD

**Issue by s1rserg** [BinaryStudioAcademy/bsa-2024-gitfit#550]
### Describe your issue

On the Contributors page, when the 'Merge' option is clicked in the contributor menu, the 'Contributor to merge with' dropdown only displays contributors from the current page's table, instead of all contributors in the system.

### Steps to reproduce

1. Go to Contributors section.
2. Click on Contributor menu "Merge" option.
3. "Click on Contributor to merge with" dropdown.
4. Pay attention to proposed options.

### What was the actual result?

Only the contributors present in the table are displayed.

### What was the expected result?

All contributors in the system are displayed.

### Put here any screenshots or videos (optional)

![image](https://github.com/user-attachments/assets/ec2358a4-6b7c-4d21-9321-22395c71e91e)
![image](https://github.com/user-attachments/assets/0b4e0d38-8242-43df-8cc8-28cafc33a258)

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Critical (S2)

**Comment by VeronikaHordus** [comment]
Looks good now 👍
