### ISSUE TITLE
fix: Project groups are not deleted from the DB after deleting the project they corresponds to

### ISSUE THREAD

**Issue by VeronikaHordus** [BinaryStudioAcademy/bsa-2024-gitfit#555]
### Describe your issue

When deleting a Project that has Project groups the Project froups are not deleted from the DB and the user who was a member of the deleted project group sees "Cannot read properties of undefined (reading 'id')" when he was added to a group in another project.

### Steps to reproduce

Pre-conditions: User A and User B exist and logged in. User A have "Manage All Projects" permission. User B have no permissions granted.

1. Login with User A and create a new project
2. Navigate to the Manage Access page of the created project
3. Create a Project group with User B as a member and any Permission type added.
4. Login with User B and observe the page look and all accessible items.
5. Go back to the account of user A
6. Delete the project created in the Step 1.
7. Go to another Project and add the User B to the Project Group.
8. Login again with the User B and observe how the page look like.
9. Check the Project groups table in the DataBase

### What was the actual result?

After deleting the Project with project groups in it, the User B (a member of the Project group) sees an error "Cannot read properties of undefined (reading 'id')".
The project groups are not deleted from the DataBase after deleting the project.

### What was the expected result?

After deleting the Project with project groups in it, the User B (a member of the Project group) sees an empthy page (no items on the sidebar as well) and the "Pending Access" placeholder message.
The project groups are deleted from the DataBase after deleting the project.

### Put here any screenshots or videos (optional)

https://github.com/user-attachments/assets/795f7c86-d1da-4cfc-8766-60c4ef276646

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Blocker (S1)

**Comment by AnnaRomaniuta** [comment]
(For QA) Check for deleting a project without created project groups.

**Comment by VeronikaHordus** [comment]
Looks good!
