### ISSUE TITLE
feat: Fix quality criteria issues

### ISSUE THREAD

**Issue by Vitaliistf** [BinaryStudioAcademy/bsa-2024-gitfit#557]
### What feature?

1. Inconsistent naming. Folder and file name does not correspond to hook name:
![Image](https://github.com/user-attachments/assets/ef6c10b0-e1af-4f92-b71f-edaff854699f)
2. Spelling mistakes:
![Image](https://github.com/user-attachments/assets/54c08520-f40d-40c7-b292-7f7ebf75fa9f)
![Image](https://github.com/user-attachments/assets/3b39f72f-f9c9-41c4-b7f2-afc18a1c7e1f)
![Image](https://github.com/user-attachments/assets/ec73d5ae-b639-43dc-96ae-5427fa245061)
![Image](https://github.com/user-attachments/assets/af024495-b39f-4d2b-9aac-432b5dca9178)
3. Inconsistent orderBy columns names case. (Change them to camelCase)
![Image](https://github.com/user-attachments/assets/97308f9f-dbb9-4532-96dc-870ddfc0e381)
Also change it in types:
![Image](https://github.com/user-attachments/assets/86683ce5-bbb4-4aa0-85a5-88e9c19fa58e)
4. Inconsistent file structure (helper should have its own folder):
![Image](https://github.com/user-attachments/assets/ab33ea21-758f-4ed1-85de-a14e3f6c06b3)
5. Inconsistency in icon filling (both svg and path elements should have fill of "currentColor"):
![Image](https://github.com/user-attachments/assets/51e11f59-ae94-40ac-a78a-649d77246a92)
P.S. Look through all the icons and fix filling everywhere. If an icon had a fill that is different from "none" or "currentColor", it should be given a color through css. Check if it looks as before.

**Comment by GvoFor** [comment]
Otherall looks good. Here are small issues I found
1. ![image](https://github.com/user-attachments/assets/8086853c-78ae-4972-9a5d-3d1f7c5d5293)
2. `permission.controller.ts` and `project-permissions.controller.ts` -- missing swagger comment above classes with "#/components/schemas/Permission" and "#/components/schemas/ProjectPermission" definitions corresponding.
Pay attention to ProjectPermission  component schema name (it's currently named "Project-permission")

**Comment by GvoFor** [comment]
Fine
