### ISSUE TITLE
fix: The user is able to view the project card without permissions, resulting in a 404 error

### ISSUE THREAD

**Issue by AnnaRomaniuta** [BinaryStudioAcademy/bsa-2024-gitfit#558]
### Describe your issue

A user without any permissions in a project is able to see the project card on the projects page, despite not having access. Additionally, attempting to access the project details page results in an 404 error.

### Steps to reproduce

Pre-conditions: Project A and B have been created.
 
1. Log in as an Admin.
2. Create a new group in Project A with "View Project" or " Edit Project", or "Manage Project" permission.
3. Create a new group in Project B, but do not select any permissions for this group.
4. Add a user who doesn't have any root permissions to these groups.
5. Log in as the user and navigate to the projects page and pay attention to the visibility of projects.
6. Go to project B details, notice the 404 error.

### What was the actual result?

The user sees cards for project B, for which he does not have permission to view details. Error 404 is displayed when trying to access project details B.

### What was the expected result?

The user should only see Project A card and should not be able to see Project B card since they have no permissions in Project B.

### Put here any screenshots or videos (optional)

![Image](https://github.com/user-attachments/assets/7675b46b-b96f-4de5-b776-28017f8c5707)
![Image](https://github.com/user-attachments/assets/85915c9c-43fc-4e07-a441-ce01e43122e1)

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Critical (S2)

**Comment by Fjortis** [comment]
@AnnaRomaniuta 
So, this is not only caused with view, it also is the same for manage and edit.

**Comment by AnnaRomaniuta** [comment]
@Fjortis Yes, I just checked, it turns out to be the same situation. Couldn't you fix that in this ticket?

**Comment by Fjortis** [comment]
@AnnaRomaniuta All good, fixed both,  will do testing then PR

**Comment by VeronikaHordus** [comment]
Looks good to me, also good error handling. Thank you!
