### ISSUE TITLE
fix: Name field allows special characters, numbers, Cyrillic in Profile Update

### ISSUE THREAD

**Issue by AnnaRomaniuta** [BinaryStudioAcademy/bsa-2024-gitfit#562]
### Describe your issue

The "Name" field in the profile update menu allows the input of special characters, numbers, Cyrillic which should not be permitted according to the validation rules.

### Steps to reproduce

1. Log in to the application.
2. Navigate to the Profile section.
3. Attempt to change the user's name by entering special characters (e.g., @, #, $, %) or numbers, or Cyrillic in the "Name" field.
4. Save the changes.

### What was the actual result?

The "Name" field in the profile update allows special characters, numbers and Cyrillic, violating the validation rules.

### What was the expected result?

The "Name" field should only accept Latin letters, hyphens, and spaces, with a minimum of 3 characters and a maximum of 50 characters. 
When entering special characters, numbers or Cyrillic, a validation message should appear "Name must contain only Latin letters."

### Put here any screenshots or videos (optional)

![Image](https://github.com/user-attachments/assets/5147e26f-4977-4378-814a-254432e994a7)
![Image](https://github.com/user-attachments/assets/383eb000-2199-49aa-a5e0-5385c0b2db83)
![Image](https://github.com/user-attachments/assets/dce56390-70db-4418-90f3-1c4c512d5bb1)

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Major (S3)

**Comment by VeronikaHordus** [comment]
Nicely done 👍
