### ISSUE TITLE
fix: Manage Project permission does not allow user to delete a Project group in this specific project on the Manage Access page

### ISSUE THREAD

**Issue by VeronikaHordus** [BinaryStudioAcademy/bsa-2024-gitfit#569]
### Describe your issue

When attempt to Delete a project group with Manage Project permission, the "You do not have permission to this resourse" error toast notification displayed.

### Steps to reproduce

Pre-conditions: User is granted with Manage Project permission. User is logged in.

1. Open the Project Manage Access page where user have Manage Project permission.
2. Create a new Project group with valid data
3. Delete the group.
4. Observe the application behaviour

### What was the actual result?

The group is not deleted and "You do not have permission to this resourse" error toast notification displayed.

### What was the expected result?

The group is successfully deleted and the Toast notification about successfull deletion displayed.

### Put here any screenshots or videos (optional)

https://github.com/user-attachments/assets/9d211b5a-8a5d-44c3-957d-f2cc8e30229c

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Critical (S2)

**Comment by AnnaRomaniuta** [comment]
Removing groups works fine now!
