### ISSUE TITLE
feat: Add an ability to create a project

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#57]
### What feature?

- [x] Add `projects` table (columns: id, name, description created_at, updated_at). Limit the name to 50 chars and description to 1000 chars.
- [x] Add model, repository, and service on the backend.
- [x] Add a controller for projects with POST /projects route.
- [x] Project name should be unique (both in db and there should be a check for this on the backend).
- [x] Add validation for the request body.

**Comment by AnnaRomaniuta** [comment]
Good job! Thanks!
