### ISSUE TITLE
fix: The Setup Analytics button is not displayed on the page for user with Edit Project permission for the specific project

### ISSUE THREAD

**Issue by VeronikaHordus** [BinaryStudioAcademy/bsa-2024-gitfit#573]
### Describe your issue

When user is granted with Edit project permission for specific Project the Setup Analytics is not accessible.

### Steps to reproduce

Pre-conditions: User is granted with Edit Project permission. User is logged is.

1. Navigate to the Project Details page of the Project where user have Edit Project permission.
2. Explore the page appearance

### What was the actual result?

The Setup Analytics button is not displayed on the page.

### What was the expected result?

The Setup Analytics button displayed on the page. (Either Setup Analytics under the Project description or for already sat up projects the "Setup Again" button on the right side above contributos list.

### Put here any screenshots or videos (optional)

https://github.com/user-attachments/assets/0baed5e4-fc02-4336-9397-17ebf9fc09bf

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Blocker (S1)

**Comment by AnnaRomaniuta** [comment]
Everything works and looks good now! Good job!
