### ISSUE TITLE
feat: Add a user popup

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#58]
### What feature?

- [x] Add a user popup.
- [x] Display an authenticated user name and email in it.
- [x] On logout click, the authenticated user (store) and token (localStorage) should be removed, and the user should be redirected to the `/sign in` page.
- [x] When a user clicks on the avatar icon, a popup should be shown.
- [x] Popup should be closed on click outside.

### Screenshots

![Image](https://github.com/user-attachments/assets/ab379f29-29e1-4384-bd00-3212bee65838)

**Comment by AnnaRomaniuta** [comment]
Good job, thanks.
