### ISSUE TITLE
feat: Add an ability to create a project group

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#71]
### What feature?

- [x] Add `project_permissions` table (columns: id, key, name, created_at, updated_at). Limit the name to 100 chars.
- [x] Add `project_groups` table (columns: id, key, name, created_at, updated_at). Limit the name to 100 chars.
- [x] Add `projects_to_project_groups` table (columns: id, project_group_id, project_id, created_at, updated_at).
- [x] Add `project_groups_to_project_permissions` table (columns: id,  project_group_id, project_permission_id, created_at, updated_at).
- [x] Add `view_project` permission (name: "View Project") through migration.
- [x] Add needed models, and services on the backend.
- [x] Add a controller for project_groups with `POST /project-groups` route
- [x] The payload for group creation should contain name, project_id, user_ids, and permission_ids. Using this payload you will need to create an item in `project_groups`, then items in `project_groups_to_permissions`, and then in `projects_to_project_groups`. 
- [x] The key should be automatically generated in the service by turning the name into snake_case.
- [x] The key should be unique for permissions and user_groups table (restriction on db level and check on the backend as well)
- [x] Add validation for request payload and path parameters
- [x] Add new tables to the db schema in readme

**Comment by liza-veis** [comment]
Projects table will be added here #57

**Comment by VeronikaHordus** [comment]
Great job, thank you 💯
