### ISSUE TITLE
feat: Add projects page

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#72]
### What feature?

- [x] Add a common page layout (should contain header and sidebar #33)
- [x] Add projects page, the route is '/' (you can remove everything that was on this page here before)
- [x] Project card will only contain a name for now
- [x] Add route to get all projects to the controller (projects table will be added here #57)

### Screenshots

![Image](https://github.com/user-attachments/assets/2120c6fc-75be-46dc-9e05-854b57fa26a1)

**Comment by VeronikaHordus** [comment]
Everything all right, Thank you <3
