### ISSUE TITLE
feat: Add an ability to view groups

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#78]
### What feature?

- [x] Add groups table on Access Management page (page will be added here #59).
- [x] Display Name, Permissions, and Created At columns.

The groups model will be added here #56 

### Screenshots

![Image](https://github.com/user-attachments/assets/b3ba9a82-7364-481a-9070-ca8d0ccf1b90)

**Comment by VeronikaHordus** [comment]
Perfect , thank you <3
