### ISSUE TITLE
feat: Generate authorization token

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#8]
### What feature?

Implement JWT token signing and verification.

https://www.npmjs.com/package/jose

- [x] Add Token service to the backend with create and verify methods
- [x] The token should store a user id
- [x] The token should expire after 24h
- [x] Return token in response to the sign-in and sign-up

**Comment by VeronikaHordus** [comment]
Perfect, good job!

**Comment by Vitaliistf** [comment]
Thanks!
