### ISSUE TITLE
feat: Add search to the project list

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#85]
### What feature?

- [x] Add search to the project list
- [x] Search should be stored in query params and handled on the backend

Projects page is added here #72 

### Screenshots

![Image](https://github.com/user-attachments/assets/07866a3e-7a47-4aa2-8542-416453a9999e)

**Comment by AnnaRomaniuta** [comment]
Everything works well. Good job!
