### ISSUE TITLE
feat: Add project page

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#86]
### What feature?

- [x] When a user clicks on a project item in the project list on the Projects page, the Project page should be opened.
- [x] For now, only a project title and description should be displayed.

The project list will be added here #72.

### Screenshots

![Image](https://github.com/user-attachments/assets/60875e6a-271f-4b5b-a02b-9ee7b0838454)

**Comment by AnnaRomaniuta** [comment]
Looks good, thanks!
