### ISSUE TITLE
feat: Add an ability to create a project

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#87]
### What feature?

- [x] Add a "Create New" button near the projects list.
- [x] On button click, the modal should be opened to create a new project.
- [x] After form submission, the new project should be added at the top of the project list.
- [x] Validation is the same as for the backend #57.

The backend part is added here #77.

### Screenshots

![Image](https://github.com/user-attachments/assets/471fc69f-b2c6-47cf-8047-ceab47bded62)

**Comment by GvoFor** [comment]
A few questions:
1. Should I create new common component `TextArea` for description? or should I adjust `Input` component somehow?
2. Maximum description length is 1000 symbols (for now), and this means that there will be "text overflow". What is expected behaviour: should description height grow? should scrollbar appear on the right edge?

**Comment by GvoFor** [comment]
Also I will need button `width` to be `150px` so I will adjust `Button` component. I'd like to do the following:

Add prop `variant` to `Button` which type will be `type ButtonVariant = "danger" | "default" | "normal" | "outlined";`
- "default" -- is the default value. It represent button, which width is flexible, i.e. its width fits min-content OR stretchs to 100% of container
![image](https://github.com/user-attachments/assets/8f6ef33f-8e45-4ca5-a900-37b314e567ce)
↑ stretched
![image](https://github.com/user-attachments/assets/7d10e817-ca07-4b58-a0e0-9b383154e668)
↑ min-content
- "normal" -- have the same styles as a default, but it's width is fixed to 150px
![image](https://github.com/user-attachments/assets/07d5607c-da6a-4338-ae78-ec9f4ffe2198)
![image](https://github.com/user-attachments/assets/3af9eb01-919f-48a8-b7d0-cc3818d21b94)
- "outlined" -- have fixed width (150px) and looks like this
![image](https://github.com/user-attachments/assets/483eae26-080c-4182-8220-1558633b2673)
- "danger" -- have fixed width (150px) and looks like this
![image](https://github.com/user-attachments/assets/bd5a537c-445f-4bf1-80c3-b13c67fcc46e)

Can I do it this way?

**Comment by liza-veis** [comment]
> Should I create new common component TextArea for description? or should I adjust Input component somehow?

let's add rows property to input and in case we pass this property, then render textarea instead

> Maximum description length is 1000 symbols (for now), and this means that there will be "text overflow". What is expected behaviour: should description height grow? should scrollbar appear on the right edge?

scroll will be ok.

> Add prop variant to Button which type will be type ButtonVariant = "danger" | "default" | "normal" | "outlined";

Variants should follow a common pattern, if we group them by appearance, then we should have a separate property for size in case we want to add it. In this case, let's make the button 100% for all cases, and in places where we need it to be fixed width we will have two options:
1. if the size is fixed, wrap button with container and add max width to it
2. if the size depends on label inside button, then instead of setting max width, add display flex with appropriate alignment 

We need to use second option for the most of the cases.

**Comment by liza-veis** [comment]
> If yes, then what hover effects should be for "outlined" and "danger" buttons?

Adding outlined and danger to variants is ok, for hover effects:
1. for outlined you probably can use a hover background as for IconButtons
2. For danger button add additional color, slightly deeper than the current one

**Comment by AnnaRomaniuta** [comment]
Good job! Thanks!
