### ISSUE TITLE
feat: Add an ability to edit user name

### ISSUE THREAD

**Issue by liza-veis** [BinaryStudioAcademy/bsa-2024-gitfit#89]
### What feature?

- [x] Add profile item to the user menu on avatar click. The popup is added here #58.
- [x] On the item click, the user should be redirected to the profile page.
- [x] The profile page should display the name, email (disabled), and update button.
- [x] The user should be able to update their name.
- [x] The update profile button should be disabled when the data hasn't changed.

### Screenshots

![Image](https://github.com/user-attachments/assets/2185bafd-861a-4654-b06a-64713a0b43e0)
![Image](https://github.com/user-attachments/assets/f43fb047-0edc-4c03-9e44-ab4d8764a14d)

**Comment by AnnaRomaniuta** [comment]
Found some minor inconsistencies, but overall everything looks good! Thank you!
